- git/remote.py
The regular expression for parsing `git fetch -v` does not handle '#' characters in branch names correctly.
> [FIX] remote.fetch: branch names may contain '#' characters

- doc/source/tutorial.rst
- git/objects/commit.py
- git/refs/log.py
- git/test/test_index.py
We could not do a commit by filling the author directly. This PR provides this functionality.
I have include test and documentation.
> Make a commit with another author

- MANIFEST.in
- doc/source/tutorial.rst
- git/cmd.py
- git/remote.py
- git/test/test_git.py
- git/test/test_remote.py
- scripts/ssh_wrapper.py
Proposed implementation for #234
I have done some manual tests, but not set up automated tests yet. I will see how it fits into your suite tomorrow if you haven't implemented it yet. :)
Let me know if something's not quite in the right place.
> Add 'sshkey' context manager

- git/index/fun.py
Otherwise commit hook might rightfully fail, as happens if
repository is e.g. git-annex repository.  See e.g. now failing
https://travis-ci.org/datalad/datalad/builds/49802394\#L1590
which seems to pass tests nicely with patch as this.
P.S. I am still unclear WTF this doesn't fail for me locally where I do run recent GitPython now...
> BF: run commit hook with repo.working_dir as cwd

- .travis.yml
For PRs or testing of other branches, we should remain in the tree as travis prepairs it.  Switching back to the state of master is somewhat ruins the point ;)
> BF: do not checkout master -- that ruins testing of PRs

- git/diff.py
If a file in a commit contains no changes (for example, if only the
file mode is changed) there will be no blob attached.  This is
usually where the filename is stored, so without it, the calling
context can not tell what file was changed.  Instead, always
store a_path and b_path on the Diff object so that information
is available.
> Store path attribute on Diff object

- git/objects/submodule/base.py
On Windows, `repo.create_submodule(...)` failed because git didn't recognize the worktree path set in `.git/modules/sub/config` (`fatal: bad config file line 6 in ./config`). This resulted in the following traceback:
```
File "F:\Dokumente\Coding\python\PyGitUp\tests\test_submodules.py", line 42, in setup
repo.create_submodule('sub', 'sub', master_path)
File "F:\Dokumente\Coding\python\.virtualenv\PyGitUp\lib\site-packages\git\repo\base.py", line 295, in create_submodule
return Submodule.add(self, *args, **kwargs)
File "F:\Dokumente\Coding\python\.virtualenv\PyGitUp\lib\site-packages\git\objects\submodule\base.py", line 417, in add
sm.binsha = mrepo.head.commit.binsha
File "F:\Dokumente\Coding\python\.virtualenv\PyGitUp\lib\site-packages\git\refs\symbolic …
```
> Fix broken worktree path with submodules on Windows

- doc/source/tutorial.rst
- git/test/test_docs.py
Also move untestable documentation out of test.
Related: #234, #242
> Replace GIT_SSH with GIT_SSH_COMMAND for SSH key management.

- git/util.py
When running a long running operation (such as a clone on a large repo),
Git may return a message indicating that it is 'Finding sources'. Since
there is no bit field value for this message, this causes a large amount
of error messages to be emitted to stderr.
This patch fixes this by adding another bit field value for this
message, FINDING_SOURCES. Derived classes can look for this op_code and
handle it appropriately.
> fix(util): Handle 'Finding sources' messages in RemoteProgress

- doc/source/changes.rst
very small typo in changelog. Reop -> Repo
> Changelog typo

- git/test/lib/helper.py
- git/test/test_remote.py
We are building packages in a sandbox that restricts network access somewhat.
Here are a couple of changes I made that should be generally useful.
a) make the git-daemon bind to localhost instead of 0.0.0.0 (aka all interfaces), as there's no reason it should be accessible from the outside
b) make the listen port configurable via an environment variable, in case it is already taken.
> git-daemon test fixes

- git/repo/base.py
I had a use case with [PyGitUp](https://github.com/msiemens/PyGitUp) where I did not want submodules to be considered when asking whether a repo is dirty. This change allows that. I am a bit unsure with the "untracked_files" part: I would think that it's not necessary, as I can't imagine an untracked submodule (how would that work? Git would not see it as a submodule), but I included this change anyway. I can of course revert it if you are sure that there can't be a relevant case.
One problem though: I could not run (and thus not write) tests as even the most current tag had test failures for me on Python 2.7.
Please let me know what you think.
> Allow submodules to be ignored in is_dirty

- git/remote.py
Rigth now only the word "fatal:" is being checked but there are also errors that start with "error:", for example:
$ git pull origin master
From github.host.com/mycompany/repo
* branch            master     -> FETCH_HEAD
Updating 49d7506..7de461c
error: Your local changes to the following files would be overwritten by merge:
mydir/myfile.txt
Please, commit your changes or stash them before you can merge.
Aborting
> While parsing errors, also detecting lines starting with "error:"

- git/cmd.py
- git/config.py
- git/objects/commit.py
- git/objects/submodule/base.py
- git/objects/submodule/root.py
When the code is run without setting up loggers, the loggers have no
handlers for the emitted messages. The logging module displays:
`No handlers could be found for logger "git.cmd"` on the
console. By adding a NullHandler (a no-op) the message disappears,
and doesn't affect logging when other handlers are configured.
> Added NullHandlers to all loggers to prevent "No handler" messages

- git/repo/base.py
Adds an additional newline in the comment of `Repo.clone_from()` in order for the docstring to be correctly parsed by Sphinx.
> Fix docstring of Repo.clone_from()

- git/repo/base.py
Adds the optional keyword parameter `env` to `Repo.clone_from()`. The parameter is a dictionary containing the desired environment variables for the git clone invocation. The environment is applied to the temporary `Git` instance before calling `Repo._clone()`.
> Add env parameter to Repo.clone_from() for setting environment variables

- git/config.py
According to the [git documentation](http://git-scm.com/docs/git-config), include.path is subject to tilde expansion.
> You can include one config file from another by setting the special include.path variable to the name of the file to be included. The included file is expanded immediately, as if its contents had been found at the location of the include directive. If the value of the include.path variable is a relative path, the path is considered to be relative to the configuration file in which the include directive was found. ***The value of include.path is subject to tilde expansion***: ~/ is expanded to the value of $HOME, and ~user/ to the specified user’s home directory. See below for examples.
So, I added to care code for tilde expansion.
> care tilde in include.path config

- git/repo/base.py
- git/test/test_docs.py
revA..revB &rarr; revA...revB (three instead of two dots) [base.py, line
467](https://github.com/gitpython-developers/GitPython/blob/master/git/repo/base.py#L467)
rorepo is a ~~a~~ Repo instance [test_docs.py, line
21](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_docs.py#L21)
closes #314
> Correct doc errors

- git/index/base.py
- git/objects/commit.py
- git/test/test_index.py
As title says, now you can send custom datetime to the commit:
```
import git
...
repo = git.Repo.init(repo_path)
repo.index.add(['some_file'])
repo.index.commit(message, authored_date=commit_date, committed_date=commit_date)
```
> Feature: Make commits with custom `author_date` and `commit_date` (closes #315)

- git/refs/head.py
If a git repo has the misfortune to have a file with the name "HEAD"
at the root level of the repo, git will return an error because it
is unsure whether the file or ref is meant:
File "/usr/local/lib/python2.7/dist-packages/git/refs/head.py", line 81, in reset
self.repo.git.reset(mode, commit, add_arg, paths, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 440, in <lambda>
return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 834, in _call_process
return self.execute(make_call(), **_kwargs)
File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 627, in execute
raise GitCommandError(command, status, stderr_value)
GitCommandError: 'git reset --hard HEAD' returned with exit …
> Always add '--' to git reset

- git/repo/base.py
- git/test/test_repo.py
Wrap `git merge-base --is-ancestor` into its own function because it acts
as a boolean check unlike base `git merge-base call`
> Implement is_ancestor

- git/objects/submodule/base.py
Without this commit the update() function of a submodule does not work
in CentOS 6.
> gic {init,clone} --separate-git-dir is supported only since 1.7.5

- git/refs/symbolic.py
SymbolicReference leaked file descriptor resources when iterating on refs. unittest module complained:
symbolic.py:153: ResourceWarning: unclosed file <_io.TextIOWrapper name='...../gitrepo/.git/packed-refs' mode='rt' encoding='UTF-8'>
symbolic.py:148: ResourceWarning: unclosed file <_io.TextIOWrapper name='....../gitrepo/.git/packed-refs' mode='rt' encoding='UTF-8'>
> Ensure file resources are released

- git/cmd.py
Fixed deadlock when using stderr=PIPE in Popen and Git generates enough
output to a pipe such that it blocks waiting for the OS pipe buffer to
accept more data (see https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait)
> fix(cmd): fixed deadlock when stderr buffer overflow

- git/cmd.py
This feature enables to set a timeout while executing a git
command. After this timeout is over, the process will be killed.
If not explicitly specified, the default functionality will not
be affected.
> Include 'timeout' parameter in Git execute

- git/util.py
As seen in #330, "Checking out files" is not covered in the operations for RemoteProgress. Here is a simple fix. I have not found where to add test for it, feel free to redirect me.
Closes #330
> Added CHECKING_OUT as a logged operation

- git/cmd.py
signal.SIGKILL is not available on Windows so use signal.SIGTERM as a backup
when SIGKILL is not available.
> Fixed a non-Windows import

- git/config.py
- git/repo/base.py
- git/test/test_config.py
- test-requirements.txt
If used as context managers, the parsers will automatically release their file locks. This was mentioned in #333 and seems like a good thing to have, as you can't forget to call `release` that way.
Another nice thing might be to use `__enter__` to re-acquire locks if necessary, so that the readers can be used in multiple contexts.
> enable config parsers to be used as context managers

- git/test/test_repo.py
as I have whined somewhere sometime ;)
> ENH: skip test_is_ancestor on git versions < 1.8.0 not supporting git merge-base --is-ancestor

- git/cmd.py
Popen in many versions of Python (possibly all versions prior to 3.3.1?) defaults to using unbuffered reads (bufsize=0), which are *extremely* slow. When reading a 160k file from git, unbuffered reads take 5.75s; buffered reads take 0.23s.
Newer versions of Python 3 appear to change the default to bufsize=-1 so this may only be a problem for a subset of users, but it certainly was a problem for me. I’m not sure of any reason not to just use buffered reads by default for everyone, so I am submitting this patch for evaluation. Thanks!
> fix(cmd): Use buffered reads

- git/config.py
- git/test/test_config.py
Building on #388 context managers can now be reentered and will lock again.
> config parsers as context mangers can now be reentered for locks

- doc/source/tutorial.rst
Trivial change. "It's" is short for "it is", while "its" is the possessive form of "it".
> Fix it's vs its in tutorial.rst

- git/cmd.py
- git/test/test_repo.py
This had tripped me up when consuming from `.read(4096)` in a streaming fashion. All chunks will return bytes except the last one (the empty string), which is a unicode string in Python 3.
This fixes that to always return bytes, in both Python 2 and 3.
> Make sure .read() and friends always return bytes

- git/compat.py
- git/repo/base.py
- git/test/fixtures/blame_incremental
- git/test/test_repo.py
This adds a sibling method to Repo's blame method:
Repo.blame_incremental(rev, path, **kwargs)
This can alternatively be called using:
Repo.blame(rev, path, incremental=True)
The main difference is that blame incremental is a bit more efficient and does not return the full file's contents, just the commits and the line number ranges.  The parser is a bit more straight-forward and faster since the incremental output format is defined a little stricter.
See the test case for an example.
I've also added support for passing `**kwargs` to git-blame, to enable passing `-C` or `-M` to it.
> Add incremental blame support

- git/remote.py
As we discussed in issue #396, the repo's fetch refspec is now only required if no explicit refspec was given as argument to `Remote.fetch()` or `Remote.pull()`.
> Remove assertion over fetch refspec when explicitly specified

- doc/source/changes.rst
- git/diff.py
- git/test/fixtures/diff_file_with_spaces
- git/test/fixtures/diff_initial
- git/test/test_diff.py
**NOTE:** This PR builds on #408, so please merge that one first.
---
The a_path and b_path cannot reliably be read from the first diff line as it's ambiguous.  From the git-diff manpage:
> _"The a/ and b/ filenames are the same unless rename/copy is involved. Especially, **even for a creation or a deletion**, /dev/null is not used in place of the a/ or b/ filenames."_
This patch changes the a_path and b_path detection to read it from the more reliable locations further down the diff headers.  Two use cases are fixed by this:
- As the man page snippet above states, for new/deleted files the a or b path will now be properly None.
- File names with spaces in it are now properly parsed.
Working on this patch, I realized the --- and +++ lines really belong to the diff header, not the diff …
> Fix diff patch parsing

- git/cmd.py
- git/test/test_git.py
Some Git command line options are allowed to be repeated multiple times. Examples of this are the -C flag which may occur more than once to "strengthen" its effect, or the -L flag on Git blames, to select
multiple blocks of lines to blame.
$ git diff -C -C HEAD~1 HEAD
$ git blame -L 1-3 -L 12-18 HEAD -- somefile.py
This patch supports passing a list/tuple as the value part for kwargs, so that the generated Git command contain the repeated options.
> Support repeated kwargs

- git/diff.py
- git/test/fixtures/diff_patch_unsafe_paths
- git/test/test_diff.py
This specifically covers the cases where unsafe chars occur in path names, and git-diff -p will escape those.
From the git-diff-tree manpage:
> 3\. TAB, LF, double quote and backslash characters in pathnames are represented as `\t`, `\n`, `\"` and `\\`, respectively. If there is need for such substitution then the whole pathname is put in double quotes.
This patch checks whether or not this has happened and will unescape those paths accordingly.
One thing to note here is that, depending on the position in the patch format, those paths may be prefixed with an `a/` or `b/`.  I've specifically made sure to never interpret a path that actually starts with `a/` or `b/` incorrectly.
Example of that subtlety below.  Here, the actual file path is `b/normal`.  On the diff file that gets encoded as …
> Fix diff patch parser for paths with unsafe chars

- git/objects/commit.py
- git/objects/util.py
- git/test/test_commit.py
- git/test/test_util.py
This adds 2 properties to commits.  Their values are derived from the existing data stored on them, but this makes them more conveniently queryable:
- authored_datetime
- committed_datetime
These return "aware" datetimes, so they are effectively companions to their raw timestamp equivalents, respectively `authored_date` and `committed_date`.
These datetime instances are convenient structures since they show the author-local commit date and their UTC offset.
(I've implemented a tzinfo subclass here manually to avoid adding a dependency to dateutil or pytz here.)
> Add support for getting "aware" datetime info

- doc/source/intro.rst
* Added the Python version requirement
* Updated URLs for other requirement
* Removed whitespace
> Update requirements doc

- git/cmd.py
Hello,
For a tool I'm writing [git-repo](https://github.com/guyzmo/git-repo), I was working with a mockup of subprocess to run regression tests for commands issued through GitPython. I've written a process similar to the VCR or Betamax libraries to define expected command calls passed through Popen. [Here](https://github.com/guyzmo/git-repo/blob/master/tests/helpers.py#L207-L209) is where I setup the mockup, and [here](https://github.com/guyzmo/git-repo/blob/master/tests/helpers.py#L295-L311) is a place where I use it.
It was working great, up until recently when I've introduced the `--progress` support. Then I've been hitting an issue where the same code would fail inconsistently between calls. Cf the [travis reports](https://travis-ci.org/guyzmo/git-repo/builds/129130635).
With a fair …
> Fix order of operators before executing the git command

- git/compat.py
- git/test/test_base.py
- git/test/test_docs.py
- git/test/test_git.py
- git/test/test_index.py
- git/test/test_repo.py
Although it's hard to see, PEP-0263 does have ws delimiting the 'coding' string.
This commit will fix the root cause of (at least) one bug: https://lists.fedoraproject.org/archives/list/eclipse-sig@lists.fedoraproject.org/thread/5XQ5JRHG6DPPMGRDU7TA2AO4EYS2H7AG/
> Need spaces in Emacs style encoding comment

- git/repo/base.py
- git/test/fixtures/blame_incremental
Fixes a bug where there could be special characters in the commit message, causing the line splits to be improperly detected when parsing the blame metadata.
This commit opts to split lines by the new line character instead of letting `splitlines()` do this. This helps catch the issue when there are special characters in the line, particular the commit summary section.
`git/test/test_repo.py` has been modified to catch this edge case. Please do run all tests or this one test in particular.
> Split lines by new line characters

- git/cmd.py
cfr. https://github.com/gitpython-developers/GitPython/pull/431/files/89ade7bfff534ae799d7dd693b206931d5ed3d4f#r64649040
cc @Byron 
I tested this in my fork on Travis; I'm running into one failing test, but it seems unrelated to this change.
Am I missing something to make the tests pass?
```
======================================================================
ERROR: test_init_repo_object (git.test.test_docs.Tutorials)
----------------------------------------------------------------------
File "/home/travis/build/boegel/GitPython/git/ext/gitdb/gitdb/test/lib.py", line 87, in wrapper
return func(self, path)
File "/home/travis/build/boegel/GitPython/git/test/test_docs.py", line 68, in test_init_repo_object
assert repo.refs['origin/master'] == …
```
> import OrderedDict from git.odict rather than directly from collections, to pix Py2.6 compatibility

- git/cmd.py
Hello. :)
This change replaces abusing the "short-circuit" property of logical operations (`cond and A or B`) with dedicated conditional expression syntax (`A if cond else B`).
Just please double-check that I didn't get the `and-or` short-circuitry logic backwards or wrong in some other way! ;)
> Use proper syntax for conditional expressions.

- git/util.py
must call the base class __init__
> Fix traceback because _seen_ops is not initialised

- doc/source/changes.rst
- git/diff.py
- git/test/fixtures/diff_patch_unsafe_paths
- git/test/test_diff.py
The diff `--patch` output parser was missing some edge case where Git would encode non-ASCII chars in path names as octals, but these weren't decoded properly.
\360\237\222\251.txt
Decoded via utf-8, that will return:
💩.txt
> Fix bug in diff parser output

- git/objects/commit.py
- git/test/fixtures/commit_invalid_data
- git/test/test_commit.py
> Add test case as example of Git commit with invalid data

- doc/source/changes.rst
- git/objects/commit.py
This PR addresses issue #457.
Ready to be merged. Please review and merge.
> Fixes #457: 'TypeError: decode() takes no keyword arguments' on Python 2.6

- git/cmd.py
I had problems with errors like:
Exception TypeError: "'NoneType' object is not callable" in > ignored
After much digging I found, that os.kill is None in this case while os still exists. No clue how Python managed to get this state, but my change fixes the problem.
> Make sure os is not even partly destroyed

- git/diff.py
- git/test/fixtures/diff_patch_unsafe_paths
- git/test/test_diff.py
> Don't choke on (legitimately) invalidly encoded Unicode paths

- git/remote.py
- git/test/test_remote.py
Both commands enable handling of a little known feature
of git, which is to support multiple URL for one remote.
You can add multiple url using the `set_url` subcommand of
`git remote`. Though listing them is also handy, so there's
a nice method to do it, using the configuration.
> Adding support for git remote set-url/get-url API to Remote

- git/cmd.py
This just wraps stdout/stderr in `safe_decode()` calls to fix #470.  Apologies for the lack of tests.
> Fix issue #470

- doc/source/changes.rst
- git/compat.py
- git/diff.py
- git/test/test_diff.py
> Store raw path bytes in Diff instances

- git/index/base.py
This is a start to fix https://github.com/gitpython-developers/GitPython/issues/468
However, I have no idea where to add tests for this. 
I couldn't find any basic test that just tests the commit, with executing hooks. Tips most appreciated.
> Commit without executing hooks, fixes #468

- git/repo/base.py
This allows GitPython and downstream projects (such as [PyGitUp](https://github.com/msiemens/PyGitUp)) to work with [yadm](https://github.com/TheLocehiliosan/yadm).
> Use $GIT_DIR when set

- AUTHORS
- git/remote.py
- git/test/test_refs.py
It makes sense to be able to write ``for ref in repo.remotes.upstream.refs`` without having to guard against an AssertionError.
Also relates to a comment from @Byron in https://github.com/gitpython-developers/GitPython/issues/480#issuecomment-228543784.
> Allowed remotes to have no refs.

- git/test/test_docs.py
The Remotes section was missing some pretty important info
> Update Remotes section

- git/remote.py
by demanding a space after a word remote, and space is explicitly described as
a delimiter in man git-config:
To begin a subsection put its name in double quotes, separated by space from the section name,
otherwise e.g.
```
File "/usr/lib/python2.7/dist-packages/datalad/support/gitrepo.py", line 836, in get_remote_branches
for remote in self.repo.remotes:
File "/home/yoh/deb/gits/python-git/git/repo/base.py", line 271, in remotes
return Remote.list_items(self)
File "/home/yoh/deb/gits/python-git/git/util.py", line 745, in list_items
out_list.extend(cls.iter_items(repo, *args, **kwargs))
File "/home/yoh/deb/gits/python-git/git/remote.py", line 453, in iter_items
raise ValueError("Remote-Section has invalid format: %r" % section)
ValueError: Remote-Section has invalid format: u'remotes'
``` …
> BF: allow for other section names which start with a string "remote"

- git/config.py
- git/index/util.py
- git/test/lib/helper.py
- git/util.py
@wraps does more and does it right ;)
> RF: use @functools.wraps within decorators instead of manual __name__ reassignment

- git/objects/submodule/base.py
- git/test/lib/helper.py
- git/test/test_submodule.py
now if there is a remote without any refs (this happens e.g. with git-annex repo with special remotes), it would refuse to remove the submodule
(with 2.0.8 it also didn't work but with a different msg "AssertionError: Remote datalad did not have any references")
> BF: remove a submodule with a remote without refs + misc fixes around

- .travis.yml
codecov in our (datalad, etc) experience provides a better service,
great support, and super-nice intergration with chromium and firefox
for reviewing coverage of pull requests.  In light of the
@with_rw_directory fiasco detected/fixed in #521 I would strongly
recommend to (re-)enable and use coverage reports
edit 1: I think that if you accept this PR codecov might automagically enable itself on this repo, but I could be wrong and someone with authority might need to login into codecov via github and enable
coverage as seen from my clone: https://codecov.io/gh/yarikoptic/GitPython/commit/94ca83c6b6f49bb1244569030ce7989d4e01495c
and trust me integration with browsers is great!    ha -- actually basic (since there were no reports against master -- can't show the difference)  report already …
> RF: coveralls (not used/relied on really) -> codecov

- git/cmd.py
- git/objects/submodule/base.py
- git/remote.py
- git/repo/base.py
- git/test/lib/helper.py
- git/test/test_base.py
- git/test/test_docs.py
- git/test/test_git.py
- git/test/test_remote.py
- git/test/test_repo.py
- git/test/test_submodule.py
- git/util.py
+ git-daemon:
+ Use git-daemon PORT above 10k; on Windows all below need Admin rights.
+ Used relative daemon-paths with `--base-pth`.
+ Simplify git-daemon start/stop/ex-hanlding.
+FIXED git-daemon  @with_rw_and_rw_remote_repo():
+ "Polish" most remote & config urls, converting \-->/.
+ test_base.test_with_rw_remote_and_rw_repo() PASS.
+ Remote: 
+ test_remote: apply polish-urls on `_do_test_fetch()` checking function.
+ test_remote.test_base() now freezes on Windows! (so still hidden win_err).
pump fetch-infos instead of GIL-reading stderr.
+ Push-cmd also keep (and optionally raise) any error messages.
+ `cmd.handle_process_output()` accepts null-finalizer, to pump completely
stderr before raising any errors.
+ test: Enable `TestGit.test_environment()` on Windows (to checks stderr …
> Start fixing #525 Windows errors

- git/cmd.py
- git/test/test_git.py
Currently `_git_options` in class `Git` are reset after each subcommand call. While this is appropriate in most cases, I'm in need to have options for the git executable, that are used with all calls to git on a certain repository and I can't provide this option for each and every call. Therefore I'd like to introduce the possibility to persistently set such options for a given instance of `Git`.
This is my first PR here, so I'm not exactly sure, what you want me to provide. `CONTRIBUTING.md` reads: "Write a test that fails unless your patch is present." 
Where am I supposed to put such a test?
Just add it to `git/test/test_git.py`?
> Allow for setting git options, that are persistent across subcommand calls

- git/repo/base.py
- git/test/lib/helper.py
+ Ignore "empty" GIT_DIR vars.
+ Improve documentation on the constructor `path` parameter.
Minor repo-code and doc correcions.
+ Expansion of paths also `osp.normalize()` them.
+ Make Repo-fields --> class-fields to avoid initializations on
construct.
+ Explain and rename `git.repo.fun.find_git_dir()` is for submodules
(`find_submodule_git_dir()`).
> FIX #535: expand also GIT_DIR var on Repo-construction

- git/test/performance/test_odb.py
- git/test/test_repo.py
- git/test/test_submodule.py
This is the matching-fix of https://github.com/gitpython-developers/smmap/pull/30
Now 2 more "hidden-errors" TCs pass in Windows (see #525):
+ TestRepo.test_file_handle_leaks()
+ TestObjDbPerformance.test_random_access()
> Stop emulating mmap on Windows

- git/util.py
This line singlehandedly has caused a slew of painful bugs for us in production since we upgraded from 2.0.8 to 2.0.9, seeing various UnicodeDecodeErrors on repositories with branches/tags/etc that have non-ASCII characters in them.  For most repos that only use the ASCII alphabet, implicit encoding and decoding is now happening, and most of the time we get lucky because they accidentally just work.
After reverting this one liner, our production issues all went away.
@ankostis What's the reason this line was included in f11fdf1d9d22a198511b02f3ca90146cfa5deb5c? It's the only module in the GitPython code base now that uses unicode literals, which makes reasoning about the code related to strings in this module rather confusing.  Could we perhaps just change the strings that _should_ be …
> Don't change the meaning of string literals

- .appveyor.yml
- .travis.yml
- git/cmd.py
- git/objects/submodule/base.py
- git/test/lib/helper.py
- git/test/test_base.py
- git/test/test_fun.py
- git/test/test_index.py
- git/test/test_remote.py
- git/test/test_repo.py
- git/test/test_submodule.py
- git/test/test_tree.py
- git/test/test_util.py
- git/util.py
- requirements.txt
GitPython 2.0.9 has some issues on Python 2.6 (see issue #540).
This PR fixes them. For details, see the commit message.
The Travis runs now pass on all Python versions including 2.6.
Please review.
> Fixes to support Python 2.6 again.

- git/repo/base.py
This fixes the documentation there: http://gitpython.readthedocs.io/en/stable/reference.html#git.repo.base.Repo.iter_commits
> DOC: minor typo

- README.md
The pip install command in documentation refers the package in lower case "gitpython" instead of the actual package name in camellcase "GitPython"
> Doc fix: Using camellcase package name in "pip install" command

- git/__init__.py
- git/cmd.py
- git/repo/base.py
- git/test/lib/helper.py
Some changes for this release:
See #553 for difficulties when working on Windows, where open file-handles actually "lock" the underlying files, and repos cannot be deleted.
More changes:
- Small pythonism on  #541, improves  docstring of `cmd._call_process()`.
- Export `gitpython.util.rmtree()` for deleting repos in *Windows* where blobs are readonly.
> Retrofit `repo` class as context-man to cleanup global mman on repo-delete

- git/cmd.py
Also this fixes resource-leak warning on Windows Python-3.5.3+:
```
D:\python-3.5.2.amd64\lib\site-packages\git\cmd.py:583: ResourceWarning:
unclosed file <_io.BufferedWriter name='nul'>
else getattr(subprocess, 'DEVNULL', open(os.devnull, 'wb')))
```
> fix(cmd): checking process.DEVNUL were needlessly opening `os.devnull`

- AUTHORS
- git/repo/base.py
- git/test/test_repo.py
This uses GIT_WORK_TREE environment variable if present.
In response to gitpython-developers/GitPython/issues/587.
Not all tests are passing on my master, but no new tests are failing with my commit.
I have added a test.
> check for GIT_WORK_TREE

- git/compat.py
a blind fix for a blind (not tested) line of code which has some variable lost from old pre-refactoring code I guess ;)
PS FWIW -- we have managed to run into it in quite a strange place, so not really sure how yet, here is our backtrace with 2.1.0 GitPython on Debian stretch
```
======================================================================
ERROR: Failure: NameError (global name 'exc' is not defined)
----------------------------------------------------------------------
File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
addr.filename, addr.module)
File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File …
```
> BF: there is no exc variable, raising NotASurrogateError if that is the right thing todo

- git/repo/base.py
- git/test/fixtures/blame_incremental_2.11.1_plus
- git/test/test_repo.py
Git version 2.11.1+ introduced extra lines into the subsequent hunk
sections for incremental blame output.  The documentation notes that
parsers of this output should ignore all lines between the start and end
for robust parsing.
> Ignore all lines of subsequent hunks until last one is found

- git/compat.py
Fixes my incorrect fix in #598 ;-)
> BF: pass original exception into replace_surrogate_encode

- git/repo/base.py
just that I saw it -- decided to "fix" ;)
> so minor that wasn't even worth my time typing this comment

- git/config.py
- git/remote.py
- git/test/lib/helper.py
- git/test/test_git.py
- git/test/test_index.py
- git/test/test_repo.py
- git/test/test_submodule.py
- git/test/test_tree.py
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
> Python 3.6 invalid escape sequence deprecation fixes

- git/remote.py
I found that a little change which affects the behavior of `git.remote.FetchInfo` as git version greater than or equal with 2.10.x. It case `git.test.test_remote.TestRemote.test_base` fails.
I figure out that a [commit](https://github.com/git/git/commit/2cb040baa6fcb8a6314a54933cbcb4d3fcb60401) of git changes  `git fetch --tags`'s output.
And it seems that that commit first appeared in git 2.10.0
```
➜  git git:(master) git log --oneline v2.9.3..v2.10.0 | grep 2cb0
2cb040b fetch: change flag code for displaying tag update and deleted ref
```
I have almost no contribution on github. Beg pardon if I am not doing it well.
> remote: compatibility with git version > 2.10

- AUTHORS
- git/exc.py
- git/test/test_exc.py
This can help shorten client code when all git exceptions are to be processed in one block.
> Add base class for package exceptions.

- git/objects/submodule/base.py
hopefully closes #613
did a quick shot, didn't do any tests besides locally:
```shell
(git)hopa:~deb/python-git[upstream-master]git
$> s=123; builtin cd /tmp/; rm -rf /tmp/gitsub; mkdir /tmp/gitsub; cd /tmp/gitsub; git init; mkdir $s; cd $s; git init; touch 1; git add 1; git commit -m msg 1; cd ..; git submodule add ./$s $s; git add .gitmodules; git commit -m "added subm $s"                                                                                                                                                                                                               Initialized empty Git repository in /tmp/gitsub/.git/                                        
Initialized empty Git repository in /tmp/gitsub/123/.git/
[master (root-commit) c883ce5] msg
1 file changed, 0 …
```
> BF: use get, not casting get_value while dealing with submodule path/url etc

- git/remote.py
Stumbled upon a `No handlers could be found for logger "git.remote"` message.
Apparently this issue has been addressed in PR #300 already. Back then `git/remote.py` wasn't included, so here is a one liner to do so.
> BF: Added missing NullHandler to logger in git.remote

- AUTHORS
- git/cmd.py
- git/repo/base.py
- git/util.py
Starting using GitPython, I quickly encountered a surprising behavior: a `Repo` instance could be initialized with a path like `~/path/to/some/repo` but a `Git` instance couldn't. And indeed, `Repo` expands the path it is given while `Git` doesn't.
This PR is an attempt at fixing this by moving the `_expand_path()` method previously defined in `repo/base.py` to and `expand_path()` method in the `util/` part, and using it both where it was already used and newly in the `Git` constructor.
> util: move expand_path from repo/base and use it in Git class init

- git/refs/remote.py
- git/refs/symbolic.py
- git/remote.py
- git/repo/base.py
- git/test/test_repo.py
Turns out aec58a9 did the right thing for /packed/ refs, but didn't work
correctly on /unpacked/ refs.  So this patch gives unpacked refs the
same treatment.
Without the fix here, the test added will cause this traceback:
======================================================================
ERROR: Check that we find .git as a worktree file and find the worktree
----------------------------------------------------------------------
File "/home/pjones/devel/github.com/GitPython/git/test/lib/helper.py", line 92, in wrapper
return func(self, path)
File "/home/pjones/devel/github.com/GitPython/git/test/test_repo.py", line 938, in test_git_work_tree_dotgit
self.assertIsInstance(repo.heads['aaaaaaaa'], Head)
File …
> worktrees: make non-packed refs also work correctly.

- git/__init__.py
This catches any raise of one of the custom exceptions defined in `git.exc` during the imports in the dunder init, and raises an `ImportError` in those cases.
This is my (perhaps naïve) attempt to fix #657.
> Fix GitError being raised in initial `import git`

- git/remote.py
And when using the API interactively, having it show up as public is
confusing.
> FetchInfo.re_fetch_result has no reason to be public

- git/objects/submodule/base.py
Fixes https://github.com/gitpython-developers/GitPython/issues/678
Seems there are a plethora of things that expect to be able to get a submodule's name. However it is not defined if `Submodule.add` finds the submodule already exists. This is one attempt at trying to solve this issue.
> Store submodule name

- git/cmd.py
We don't properly encode our error message under python3.
Signed-off-by: Paul Belanger <pabelanger@redhat.com>
> Fix encoding issue with stderr_value and kill_after_timeout

- git/refs/symbolic.py
Related to issue 687.  I also had the problem after updating my git version.
Please feel free to remove all the comments explaining the change.
I must admit this is the first time I've looked at the git source, so I may not have done this right.  But, it works for me : -)
as long as line contains "peeled", accept it
fixes the PackingType of packed-Refs not understood:
problem
> recognize the new packed-ref header format

- AUTHORS
- git/repo/base.py
- git/test/test_repo.py
In case eg pathlib.Path is passed.
Fixed #684
> Converting path in _clone to str before any other operation

- git/repo/base.py
Under Windows, tempfile objects are holding references to open files
until the garbage collector closes them and frees them.  Explicit
calls to gc.collect() were added to the finalizer for the Repo class
to force them to be closed synchronously.  However, this is expensive,
especially in large, long-running programs.  As a temporary measure
to alleviate the performance regression on other platforms, only
perform these calls when running under Windows.
Fixes #605
> Only gc.collect() under windows

- git/index/base.py
- git/index/fun.py
- git/test/test_index.py
> commit-msg hook support

- git/remote.py
> Fixes issue #694

- AUTHORS
- git/objects/submodule/base.py
- git/test/test_submodule.py
> Remove trailing slash on drive path

- git/index/base.py
This version check only checks the minor number: the `y` in Python `x.y`.
So mmap is available for Python 2.6 and 2.7, and 3.6+, but not for 3.0 to 3.5.
But I think the intent was to have memory maps for Python 2.6 and up, including all of Python 3.x (and 4.x etc.).
As Python 2.6 is the minimum supported version, the `allow_mmap` is always `True` for supported versions.
> Allow mmap not just for py2.6, 2.7 and 3.6+ but also 3.0+

- git/index/base.py
- git/test/test_index.py
Fixes #743
Signed-off-by: Ruslan Kuprieiev <kupruser@gmail.com>
> git: index: base: use os.path.relpath

- git/cmd.py
- git/test/test_repo.py
> Configurable chunk size

- git/__init__.py
This is related to my fix in #658. Apparently, MacOS adds a git executable that is just a stub which displays an error. This gets past the try/except I added in #658, and allows all of the GitPython components to be imported, but since the executable is not *actually* git, it results in an exception when ``refresh()`` attemepts to run a ``git version``.
Fixes #762.
> Fix exception on import in MacOS

- git/cmd.py
- git/test/test_git.py
This fixes issue #619 - raise GitCommandError(not TypeError) when output_stream is set
in `git.execute(...)`.
> Fix TypeError in git.execute(..., output_stream=file)

- AUTHORS
- git/repo/base.py
- git/test/test_repo.py
Among other things, remotes are now correctly identified when in a separate worktree.
> Respect _common_dir when finding repository config file

- git/repo/base.py
Hi @Byron,
I am a co-worker of @Farom and we need his PR #801 merged for one of our future projects. He had no time to add the last feedback so i edited his patch.
> read workdir from git.config as referenced in man 1 git-config

- git/diff.py
The renamed_file function contains the following which ends up on readthedocs: 
:note: This property is deprecated, please use ``renamed_file`` instead.
Removed the line
> Fixed error in documentation

- git/test/test_remote.py
When we added the xenial image on Travis CI, it came with a git upgrade.  Xenial usually has git 2.7.4 but the one on travis has 2.20.1.  In version 2.20 there were changes around how tags can be clobbered (or not):
https://github.com/git/git/commit/0bc8d71b99e91c9e90b519073b639a5066119591
The test suite was relying on the old behavior, so we had to adjust the test.
> Fix test-only issue with git 2.20 or later handling a clobbered tag

- git/repo/base.py
This is a non-functional change intended to offer guidance to Windows users.  It's a little confusing that, say, `C:\GitHub\GitPython` is not a valid Git repository - the Repo object seems to expect a `.git` directory during initialization.
> Added usage example to Repo __init__.py call for Windows users

- AUTHORS
- git/objects/commit.py
Closes #806: author parameter requires Actor type, not string.
Updates documentation to reflect this.
> Fix commit.py documentation

- dockernose.sh
- git/test/test_remote.py
> Resolve test incompatibility with git v2.21.0

- setup.py
Originally detected while running DataLad tests on CRON  https://github.com/datalad/datalad/issues/3395 although mystery remains why not earlier.
To say the truth I am not fan of the approach (defer to reading requirements.txt) introduced in ce21f63 but I guess it is a separate issue
> BF: install_requires not just requires for setup() call

- git/repo/fun.py
Normalize path after joining submodule path and the relative path to the git dir, to eliminate path length errors on Windows
> Fix for issue #876

- .travis.yml
- doc/requirements.txt
- doc/source/conf.py
Currently `make html` will output pages without styles
or different from the online documentation.
With this change the local documentation looks the same as the online
documentation.
> Build docs locally

- git/objects/submodule/base.py
- git/test/test_submodule.py
Fix #279
When the path doesn't exist, gitpython throws an error, this usually happens when the user deletes the submodule directory but not the submodule entry in `.gitmodules`.
> Fix submodules listing error

- AUTHORS
- git/util.py
Running code like `'origin' in git.Repo('path/to/existing/repository').remotes`
raises an AttributeError instead of returning a boolean. This commit fixes that
behaviour by catching the error when doing an identity match on `IterableList`.
Minimum test case with version 2.1.11:
```python
>>> 'origin' in git.Repo('path/to/existing/repository').remotes
File "<stdin>", line 1, in <module>
File "/home/cesar/.local/lib/python3.7/site-packages/git/util.py", line 867, in __contains__
rval = list.__contains__(self, attr)
File "/home/cesar/.local/lib/python3.7/site-packages/git/remote.py", line 451, in __eq__
return self.name == other.name
AttributeError: 'str' object has no attribute 'name'
```
> Fix `AttributeError` when searching a remote by name

- .appveyor.yml
- test-requirements.txt
- tox.ini
Python 2 support was dropped, there is not need to run tests in py2
> Remove python 2 from CI

- git/cmd.py
- git/test/test_git.py
While working on our project I found that `old_repo.git.rev_list('HEAD', max_parents=0)` started to work differently after the new release of GitPython and our tests started to fail. After some debugging I found the problem. Kwargs were not transformed correctly if a value was set to 0 due to wrong if condition:
```
>>> 0 not in (False, None)
False
>>> 0 is not False and 0 is not None
True
```
The commit also contains a test for the edge case.
> Fix Git.transform_kwarg

- git/repo/base.py
- git/test/lib/helper.py
It fixes config file finding when in a separate worktree.
If fixes the issue with worktree reported in https://github.com/gitpython-developers/GitPython/issues/719#issuecomment-362232645
> use git rev-parse to look for config file

- git/repo/base.py
`mutli_options` -> `multi_options`
> Fix typo in documentation

- AUTHORS
- git/repo/base.py
- git/test/test_repo.py
This will be useful to me at least. This way, I know that I can tell
my script to omit some specific commits. If you accept to merge it, I
may also do similar method for merges and cherry pick.
> Method stating which commit is being played during an halted rebase

- git/objects/commit.py
Fix #915. Originally opened in ishepard/pydriller#58.
It turns out that `commit.py` already has a `default_encoding` field set to 'UTF-8'. This was probably a leftover from previous versions.
> Fix UnicodeDecodeError in gpgsig

- git/test/test_index.py
Test hooks are created with a `sh` shebang: https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_index.py#L53
however in `sh` `echo` doesn't always support `-n`, and can print it out:
```
$ bash -c "echo -n hello"
hello # <- no newline here
$ sh -c "echo -n hello"
-n hello # <- newline here
```
Instead of `echo -n` use `printf` which works correctly in all `sh`s.
> Fix test_commit_msg_hook_success.

- git/test/test_remote.py
`git` will sometimes print out empty progress lines.
> Remove assert that can fail erroneously.

- git/remote.py
- git/test/test_remote.py
Successful branch deletions look like
```
-	:refs/heads/test-delete	[deleted]
```
however rejected branch deletions look like
```
!	(delete):refs/heads/test-delete	[rejected] (stale info)
```
for some reason. Parse those as well.
> Parse rejected deletes.

- git/util.py
Universal newlines means that the streams will split on `\r` just like any other kind of newline, so there is no need to handle them differently.
> Take advantage of universal newlines.

- git/remote.py
We can't use `'foo' in repo.remotes` syntax in current version, but `'foo' in repo.refs` works fine.
It raises `AttributeError` before it runs full name search:
```py
In [2]: r = git.Repo('.')
In [3]: 'origin' in r.remotes
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-800621fb1c9b> in <module>
----> 1 'origin' in r.remotes
~/Projects/GitPython/git/util.py in __contains__(self, attr)
865     def __contains__(self, attr):
866         # first try identity match for performance
--> 867         rval = list.__contains__(self, attr)
868         if rval:
869             return rval
~/Projects/GitPython/git/remote.py in __eq__(self, other)
449
450     def __eq__(self, other): …
```
> Fix error on comparing git.Remote

- git/util.py
The logic to strip away ansi control sequences only works if they're at the end of the line, if the control sequences are at the beginning of the line the whole line will be stripped away, and all progress information will be lost.
> Remove control character stripping.

- git/repo/base.py
Related to #924, https://github.com/iterative/dvc/issues/2471
> git: repo: base: update clone_from env argument description

- AUTHORS
- git/diff.py
- git/test/fixtures/diff_copied_mode
- git/test/fixtures/diff_copied_mode_raw
- git/test/test_diff.py
This addresses #932 by adding support for the 'C' (copied) change type.
I used the repro case provided in the issue as the basis for the new test that covers this addition.
> Add support for 'C'-type diffs

- git/objects/util.py
- git/test/test_util.py
> Fix pickling of tzoffset

- git/cmd.py
- git/diff.py
- git/test/test_diff.py
- init-tests-after-clone.sh
This PR addresses the issue reported in #891
The problem was that `Diff` was receiving the parent `Repo` but commit hashes from the submodule repo, resulting in `Diff` being unable to find the commits. This was due to the output of `git diff-tree <parent_commit_1> <parent_commit_2>` containing the hashes from the submodule:
```
$ git diff-tree 53a7920fe21c49edb4471978361c1f23bf4034b1 d4f583c621da537db510ee19b2198d2192df84a9
:160000 160000 8324c24a8c6d60bd83a5356e81e5278e54ef49fc 5ac7216dccc0c1352d53a17efbc5b3bfafc0fd46 M	sub
```
This implementation fixes that issue by comparing the `a_rawpath` to all of the repo's submodule `path`s and overwriting `repo` to the submodule's repo if there's a match. If there are ideas concerning a more efficient way to identify this situation I'm more than …
> Fix how Diff handles commits that contain submodule changes

- git/diff.py
- git/test/test_diff.py
This PR resolves the issue reported in #852 
As @jadinm correctly identified in #852, this bug centers around the fact that the regex utilized by `_index_from_patch_format()` in `git/diff.py` always expects the first line of the diff to have the `a` file first, then `b`:
```
diff --git a/the_file.py b/the_file.py
```
When the `other` passed to `repo.index.diff(other)` is not `None` the `-R` argument is added to the git command, resulting in the positions of the `a` and `b` files being flipped in the output and causing the `_index_from_patch_format()` function invoked by the `create_patch` option to not find a regex match:
```
diff --git b/the_file.py a/the_file.py
```
This fix makes the regex slightly more permissive, allowing it to match either order of the `a` and `b` files in the …
> Fix repo.index.diff("HEAD", create_patch=True) always returning an empty list

- git/cmd.py
> Added exception handling for WinError6

- AUTHORS
- README.md
You can view the Git Gud project at https://github.com/bthayer2365/git-gud
I've been working on it for about a month now. It's basically a CLI game that helps people learn how to use git. We're currently in pre-release on PyPi and are actively adding more levels.
I also added myself as a contributor due to PRs #949 and #950
> Added Git Gud to projects

- git/remote.py
- git/test/test_remote.py
This PR addresses #820 
As identified in the issue, running the following short script:
```
import git
git_client = git.Repo.clone_from(your_favorite_repo, 'test_clone')
result = git_client.remotes.origin.push()
print(result.summary)
```
Results in an exception like:
```
File "/home/jj/scratch/GitPython/git/jjtestfile.py", line 4, in <module>
print(result.summary)
File "/home/jj/scratch/GitPython/git/util.py", line 877, in __getattr__
if getattr(item, self._id_attr) == attr:
AttributeError: 'PushInfo' object has no attribute 'name'
```
This is a bit of a misleading exception because `results` is actually an `IterableList(PushInfo, ...)`, not an instance of `PushInfo`. The implementation of `IterableList` is looking for the `name` attribute on the items …
> Fix 'PushInfo' object has no attribute 'name'

- git/config.py
fixes #775 
We can instantiate a GitConfigParser with no files specified, if we do so, then it'll figure out where those files are. It does this by either having a `config_level` specified to it or, in the case of a config reader, by default we might want to read from all configuration levels, just like is currently the case in Repo.config_writer(), so we iterate through all of them (except repository level) and add all files to the parser. 
If the repository level is specified, we raise a unique ValueError telling the user to use the Repo object instead.
> Global ConfigParser

- git/cmd.py
- git/test/test_repo.py
Fix cloning to directories with a path containing Unicode characters
Closes issue #920
> Fix cloning to path with unicode

- git/diff.py
If you don't set the recursive option when you git clone
The following error:
```
Exception in thread Thread-1:
File "/usr/local/lib/python3.7/site-packages/git/objects/submodule/base.py", line 1037, in module
repo = git.Repo(module_checkout_abspath)
File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 184, in __init__
raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Users/tanaga/Inci_e3b_modules/Agents_e3b
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 92, in pump_stream
handler(line)
File "/usr/local/lib/python3.7/site-packages/git/diff.py", line 534, in handle_diff_line
'', change_type, score) …
```
> Check if submodule exists before referencing

- setup.py
The [Python packaging specifications](https://packaging.python.org/specifications/core-metadata) indicate that the [`license` parameter](https://packaging.python.org/specifications/core-metadata/#license) to `setup()` should be used in one of the following cases:
* the license is not a selection from the “License” Trove classifiers
* to specify a particular version of a license which is named via the `Classifier` field
* to indicate a variation or exception to such a license
This PR removes the explicit `license` parameter since the usage for this project does not fit any of those cases and it makes it more difficult to use tools like [pip-licenses](https://pypi.org/project/pip-licenses) since it is not consistent with other projects that just have `License :: OSI Approved :: BSD License` …
> Remove duplicate license parameter

- git/repo/base.py
I ran into the same issue as @kamadoatfluid in #832, as I have a mounted disk path including a `$` (valid file & folder character in most operating systems, as is `%`). Since this is intended to catch environment variables per #662, I propose the use of regex instead to prevent irrelevant warnings from cluttering logs/console output. 
This PR supports all expansion conventions demonstrated in [`os.path.expandvars`](https://docs.python.org/3/library/os.path.html#os.path.expandvars), and also aligns with environment variable naming specifications. Illegal variables simply will cause errors and therefore don't present a security risk: word characters only, beginning with `a-z` or `_`.
Supported formats:
- `% APPDATA %` or `%APPDATA%`
- `$MYVAR`
- `${MYVAR}`
> Avoids env var warning when path contains $/%; fix #832

- AUTHORS
- git/objects/util.py
- git/test/test_repo.py
The git pre-commit hook is run with the `GIT_AUTHOR_DATE` environment variable set.
The format used (on my machine anyway) is `@1574863356 +0100`, which is not handles correctly by [`parse_date`](https://github.com/gitpython-developers/GitPython/blob/master/git/objects/util.py#L150). 
This PR fixes that crash, but it doesn't quite fully resolve issue #963. This issue also contains steps to reproduce and a stacktrace.
> Added parsing for '@1400000000 +0000' date format as used by git commit hooks

- Dockerfile
Replacing the redacted MAINTAINER tag with the corresponding label. I also added a description.
> Replace redacted MAINTAINER with LABEL

- git/repo/base.py
Signed-off-by: Chenxiong Qi <qcxhome@gmail.com>
This fixes the format:
`
The Commit object for the specified revision :param rev: revision specifier, see git-rev-parse for viable options. :return: git.Commit
`
> Fix param format of Repo.commit

- git/util.py
This address a rare race condition where the directory is created by simultaneous processes both trying to create things under the same folder.
https://github.com/ansible/awx/issues/6119
```
File "/awx_devel/awx/main/tasks.py", line 2255, in make_local_copy
source_branch = git_repo.create_head(tmp_branch_name, scm_revision)
File "/venv/awx/lib/python3.6/site-packages/git/repo/base.py", line 389, in create_head
return Head.create(self, path, commit, force, logmsg)
File "/venv/awx/lib/python3.6/site-packages/git/refs/symbolic.py", line 546, in create
return cls._create(repo, path, cls._resolve_ref_on_create, reference, force, logmsg)
File "/venv/awx/lib/python3.6/site-packages/git/refs/symbolic.py", line 513, in _create
ref.set_reference(target, logmsg)
File …
```
> Do not error in race condition of directory existing

- git/objects/submodule/base.py
When git HEAD refs is broken, it raise BadName exception.
so submodules logic which is using a rev_parse function to HEAD get Exception, so handle BadName to return empty list 
https://github.com/gitpython-developers/GitPython/commit/b303cb0c5995bf9c74db34a8082cdf5258c250fe
https://github.com/gitpython-developers/GitPython/blob/b303cb0c5995bf9c74db34a8082cdf5258c250fe/git/diff.py#L281-L287
> #993 fix: wrong refs 'HEAD' exception

- git/remote.py
When fetching repos with many remotes, the verbose flag (ie. v=True) in the body of the git.remote.Remote.fetch method produces a lot of output that isn't necessarily needed.
Adding a "verbose" kwarg to the method signature would make verbosity optional.
> Remove forced verbosity when fetching from a remote

- git/remote.py
At first I thought to provide special treatment to git config lines and
otherwise keep raising uncaught exception, but then decided that it might be
better to loose some progress information than to crash.
Also _get_push_info below is doing similarish catching of all exceptions
(although doesn't even log them).
With this change, log (if enabled and not suppressed) would show
[WARNING] Git informed while fetching: git config pull.rebase false  # merge (the default strategy)
in the case of recently introduced change to the output in the following
git commit :
d18c950a69f3a24e1e3add3d9fc427641f53e12b is the first bad commit
commit d18c950a69f3a24e1e3add3d9fc427641f53e12b
Author: Alex Henrie <alexhenrie24@gmail.com>
Date:   Mon Mar 9 21:54:20 2020 -0600
pull: warn if the user didn't say …
> BF: tolerate errors while parsing fetch lines

- git/cmd.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
> Fix exception causes in cmd.py

- doc/source/tutorial.rst
PR for https://github.com/gitpython-developers/GitPython/issues/1032
Fix for bug introduced in https://github.com/gitpython-developers/GitPython/pull/1031.
> Fixed broken paths in tutorial documentation

- doc/Makefile
- doc/source/changes.rst
- git/index/base.py
- git/objects/submodule/base.py
- git/remote.py
- git/repo/base.py
- git/util.py
This fixes all the current warnings when building the documentation and updates the `Makefile` to treat warnings as errors.
In reference to: https://github.com/gitpython-developers/GitPython/pull/1033
> Treat warnings as errors when building documentation

- git/refs/symbolic.py
Deleting a symbolic ref with e.g. the name 'refs/remotes/origin/mas'
would also delete 'refs/remotes/origin/master' if the ref had to be
deleted from the pack file.
In order to fix this the full ref is now checked for a match.
> Ensure only fully matching symrefs are deleted

- AUTHORS
- git/objects/util.py
- test/test_util.py
There's no easy way to re-create a commit (i.e. for rewriting purposes), because dates must be formatted as strings, passed, then parsed back.
This patch allows `parse_date()` to accept datetime instances, such as those produced by `from_timestamp()`.
Re-creating a commit is then possible:
~~~ python
Commit.create_from_tree(
repo=commit.repo,
tree=commit.tree,
message=commit.message,
parent_commits=commit.parents,
author=commit.author,
author_date=commit.authored_datetime,
committer=commit.committer,
commit_date=commit.committed_datetime,
)
~~~
> Accept datetime instances as dates

- AUTHORS
- git/config.py
- git/repo/base.py
- test/test_config.py
Closing #1053 
Read conditional includes as defined in:
https://git-scm.com/docs/git-config#_conditional_includes
> Read conditional include

- git/repo/base.py
- test/test_repo.py
It's possible to specify a pathspec (eg :!foo) to git diff/status/...
but it currently fails with:
git.exc.GitCommandError: Cmd('/usr/bin/git') failed due to: exit code(128)
cmdline: /usr/bin/git diff --abbrev=40 --full-index --raw :!foo
stderr: 'fatal: ambiguous argument ':!foo': unknown revision or path not in the working tree.
Add missing '--' to the arguments to fix this ambiguity
Fixes: #1061 
Signed-off-by: Arnaud Patard <apatard@hupstream.com>
> git/repo/base.py: is_dirty(): Fix pathspec handling

- git/repo/base.py
Using [git check-ignore](https://git-scm.com/docs/git-check-ignore) in order to find whether paths are ignored or not in .gitignore
> Find paths ignored in .gitignore

- git/util.py
- test/test_util.py
Calling getpass.getuser may lead to breakage in environments where there
is no entries in the /etc/passwd file for the current user.
Setting the environment variables for the git user configurations should
prevents GitPython from using values from /etc/passwd. However, doing so
will not prevent reading /etc/passwd and looking for an entry with the
current user UID.
This patch changes the behavior described above so GitPython will
perform a lazy evaluation of /etc/passwd, only doing so when the
environment variables for the git user configuration are not available.
Signed-off-by: Athos Ribeiro <athos@redhat.com>
> Get system user id in a lazy manner

- git/util.py
- test/test_util.py
In c96476b, the new default_name nested function does not contain a
retun statement. This leads to an issue when the environment variables
are not present, where the actor name would not be set.
Signed-off-by: Athos Ribeiro <athos@redhat.com>
> Fix default actor name handling

- git/diff.py
Fix for #1081.
If the filename of a diff object contained non UTF-8 chars, GitPython was raising a UnicodeDecodeError.
This PR fixes this by using the "replace" flag when decoding.
Furthermore, the variable `defenc` is used, that is `sys.getfilesystemencoding()`.
> Fix UnicodeDecodeError in diff filename

- git/objects/submodule/base.py
Define git environment in submodule add/update methods
Basically just propagating the `env` dictionary to the `clone_from` invocation inside submodule add/update methods. Does that make sense to merge upstream?
> WIP: Added ability to define git environment in submodule add/update methods

- git/repo/base.py
There is a small typo in git/repo/base.py.
Should read `repository` rather than `repostory`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, repostory -> repository

- git/cmd.py
Currently, using `git.cmd.Git` with `universal_newlines=True` throws a `TypeError`:
```
In [1]: import git
In [2]: git.__version__
Out[2]: '3.1.7'
In [3]: g = git.cmd.Git()
In [4]: g.ls_files(universal_newlines=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-dc77db814df8> in <module>
----> 1 g.ls_files(universal_newlines=True)
~/venv/lib/python3.6/site-packages/git/cmd.py in <lambda>(*args, **kwargs)
540         if name[0] == '_':
541             return LazyMixin.__getattr__(self, name)
--> 542         return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
543
544     def set_persistent_git_options(self, **kwargs): …
```
> Fix universal_newlines TypeError

- git/diff.py
- test/test_diff.py
It's follow-up of #1101.
Fixes #1099
> Add '-z' on top of '--raw' to avoid path name mangling

- git/index/base.py
However, the test asserts on the provided context to be correct,
which is hard to do in this branch while it's easy to doubt the value
of this.
Lastly, there seems to be no way to ignore errors in `git` without
muting all output, which is in fact parsed.
~~Maybe it's possible to ignore errors while parsing the new kind of
error message.~~
It looks like one would have to parse `stderr` to understand what happened, maybe a code refactoring could do that.
> First attempt to fix failing test of #1103

- doc/source/intro.rst
The package uses PascalCase on pypi. Having the wrong name in the docs is confusing.
> Fix package name in intro docs to reflect actual pypi name

- git/remote.py
`FETCH_HEAD` is one of the symbolic references local to the current
worktree and as such should _not_ be looked up in the `common_dir`. But
instead of just hard coding the "right thing" (`git_dir`) lets defer this
to the `SymbolicReference` class which already contains this knowledge in
its `abspath` property.
This was introduced by #654. I suspect an overzealous search & replace of `git_dir` -> `common_dir` was the cause here.
FYI: this bug can be reproduced by this Python script. I've not been able to convert that into a test case though:
```python
import logging
import os
import os.path
from tempfile import TemporaryDirectory
import git
logging.basicConfig(
level=logging.DEBUG,
)
with TemporaryDirectory() as tmpdir:
with git.Repo.init(os.path.join(tmpdir, "source"), expand_vars=False) …
```
> fix(fetch): use the correct FETCH_HEAD from within a worktree

- git/cmd.py
Add __next__ method to git.cmd.Git.CatFileContentStream, so it can actually be used as an iterable
> Make git.cmd.Git.CatFileContentStream iterable

- git/objects/commit.py
- test/test_commit.py
The iterator used to yield Commit() objects, which does not play well
with inheritance. Yield cls() instead.
Signed-off-by: Yuri Volchkov <yuri@volch.org>
> Fix inheritance issue at commit.iter_items

- git/objects/commit.py
- test/test_commit.py
This adds a replace method to git.Commit. The replace method returns a
copy of the Commit object with attributes replaced from keyword
arguments. For example:
```
>>> old = repo.head.commit
>>> new = old.replace(message='This is a test')
```
closes #1123
> add replace method to git.Commit

- doc/source/changes.rst
Thanks for the kind words on #1124! This PR adds a changelog entry, although I wasn't quite sure what you wanted that to look like for a future release. I noticed there were two entries for 3.1.12, and following the links it looks like the latest should have been 3.1.13 so I fixed that while I was there.
> add a changelog entry for #1124

- git/refs/symbolic.py
> Use UTF-8 encoding when getting information about packed refs

- git/cmd.py
Since Python 3.6 kwargs are stable ordered again and Python 3.5 reached
its end-of-life too, so we can revert 89ade7bfff534ae799d7dd693b206931d5ed3d4f
again. Thus make it able to pass ordered options to Git commands again.
>  Restore order of operators before executing the git command only for < py3.6

- doc/source/changes.rst
- git/__init__.py
- git/cmd.py
- git/compat.py
- git/config.py
- git/db.py
- git/diff.py
- git/exc.py
- git/remote.py
- git/repo/base.py
- git/util.py
- test-requirements.txt
Added types to:
git.__init__.py, 
compat.py, 
db.py, 
diff.py,
exc.py, 
util.py
Passes mypy and pyright checks
Also some suggested fixes from #1192
> Add more types

- git/cmd.py
- git/repo/base.py
- git/util.py
- test/test_repo.py
- test/test_util.py
Currently, if you use a git URI containing a password like `https://username:pass@git.example.com/project` and an exception occurs during a git clone the password is printed in the logs. It also happen when the logging is at debug level.
To avoid secrets to leak in the logs, this patch replace the password by a fix amount of stars (`******`).
> Replace password in URI by stars if present to avoid leaking secrets in logs

- git/cmd.py
> Set daemon attribute instead of using setDaemon method that was deprecated in Python 3.10

- git/remote.py
Remove windows special handling when creating Remote
Python2.5 is no longer supported, and it will cause a problem when init Remote with a no remote git repo.
> Remove windows special handling

- git/repo/base.py
- test/test_clone.py
Try to fix #1221
The `to_progress_instance` function will convert `None` to `RemoteProgress` instance, so the line `if progress_checked` is True if `progress` parameter is `None`.
> Fix missing stderr when the progress parameter of _clone is None

- git/types.py
This should make our internal PathLike type compatible with Python < 3.6 and < 3.9.
Fixes #1219
> fix(types): get the os.PathLike type as correctly as possible

- .github/workflows/pythonpackage.yml
- MANIFEST.in
- git/cmd.py
- git/compat.py
- git/config.py
- git/exc.py
- git/objects/__init__.py
- git/objects/base.py
- git/refs/reference.py
- mypy.ini
- tox.ini
This is intended to (partially) address the CI concerns expressed in #1219 and #1223 and will result in _partial_ type checking of the type annotations by using mypy. Keep in mind though that mypy is performing _best-effort static_ analysis in a _dynamically typed_ language so it can only partially check for correctness.
Some other tool(s) will be needed to have more complete type checking at runtime. E.g. [typeguard].
In order to get mypy running successfully this also makes a few (as little as possible) changes to the type annotations. The mypy setting to require annotations on everything is commented out because there's way too much functions lacking annotations right now.
[typeguard]: https://pypi.org/project/typeguard/
> ci: check types with mypy

- git/cmd.py
- git/compat.py
- git/config.py
- git/diff.py
- git/exc.py
- git/repo/base.py
- git/types.py
- git/util.py
- mypy.ini
Adding types to config.py and cmd.py
Functions annotated all listed in commit titles.
I had to use a few casts in this one, due to the use of hassattr to distinguish strings from file objects. 
If anyone knows a better way, let me know. (Its an open issue on mypy, and Guido recomends rewriting and doing type checks - a job for the future!) https://github.com/python/mypy/issues/1424#issuecomment-223795437
Some minor logic changes, all for type checks (e.g. because str is a subtype of Sequence, have to check for it before other sequences) or to try to separate strings from bytes.
All check pass and mypy happy. I also ran some basic scripts against it, and no errors.
Might be worth cutting a release after this PR, in case an errors are hiding?
(No rush, I only submitted this one so fast as …
> Add types to git/config.py

- git/util.py
Hopefully to fix #1238. 
The orginal change (commit 39eb0e6) was attempting to get mypy consistant with expand_path(None), as it doesn't like try except blocks without some type narrowing and expanduser doesn't accept None (triggering the Exception). Added mypy ignores for now, to allow CI to pass.
It passes tests either way, so can't be sure, but the traceback points to an overload of cmd.Git.excecute(), wherein cwd = self._working_dir.  
That leads to Git.__init__(), where self._working_dir = expand_user(working_dir)
> revert util.expand_path() due to regression

- git/cmd.py
- git/db.py
- git/diff.py
- git/exc.py
- git/index/base.py
- git/index/fun.py
- git/index/typ.py
- git/index/util.py
- git/refs/log.py
- git/repo/base.py
- git/repo/fun.py
- git/util.py
Added types to Index submodule,
plus change some types in othe files to make them agree
> Added types to Index submodule

- git/util.py
> fixed case where progress was no longer shown if a single error occured

- git/index/fun.py
- test/test_fun.py
As noted in #1253, this area could use some tests.  Any help is appreciated there.
> improve index mode for executable files

- git/remote.py
> Don't raise on unknown line when parsing stale refs (#1262)

- AUTHORS
- git/refs/tag.py
- git/repo/base.py
- test/test_repo.py
> Issue 1261

- git/repo/base.py
- test/test_repo.py
As discussed in #1266.
Unfortunately `git cat-file --batch-check` doesn't allow for specific object limits like `git cat-file commit --batch-check`,
I did not know this at first and added `cat_file_blob_header` parallel to `cat_file_header`, to basically check a smaller subset of objects.
An improvement that could be made, if the check takes too long on big repos, would be to split the cat_file_header object collection into object collections per type. That way only a subset of objects would be queried after the initial query for the cat_file_header collection.
> Adds repo.is_valid_object() check.

- git/objects/submodule/base.py
There was a small typo bugging me ;).
> Fix exsit typo

- git/objects/submodule/base.py
- test/test_submodule.py
The purpose of the change is to add multiple_options for clone in Submodule simmilar as it is done in the Repo.clone().
> Added clone multi_options to Submodule

- .gitignore
- git/cmd.py
- git/config.py
- git/diff.py
- git/index/base.py
- git/index/fun.py
- git/index/util.py
- git/objects/commit.py
- git/objects/fun.py
- git/objects/submodule/base.py
- git/objects/submodule/root.py
- git/objects/submodule/util.py
- git/objects/tree.py
- git/objects/util.py
- git/refs/head.py
- git/remote.py
- git/repo/base.py
- git/types.py
- git/util.py
- mypy.ini
* Finished adding initial types to Index and Submodule modules
* Gone back to try and improve types in various places, especially git/diff.py objects.tree and Traversable
* Renamed 'diff' in various places (I think none user facing) to distingish the submodule from the function and the variables.
* Added some TypeGuards (is_config_level()) and Protocols (Has_Repo, Has_id_attribute)
* Removed 'out_append = out.append' in a couple of places, just because they prevent getting info on hover in IDEs
* Made IterableList ___getattr___ return type same as the list was initialised with, , which is not strictly correct but better than Any.
> Finish initial typing of Index and Submodule

- .flake8
- git/compat.py
- git/config.py
- git/diff.py
- git/index/fun.py
- git/index/typ.py
- git/objects/commit.py
- git/objects/submodule/base.py
- git/objects/submodule/util.py
- git/objects/tree.py
- git/refs/reference.py
- git/refs/symbolic.py
- git/remote.py
- git/repo/base.py
- git/types.py
- requirements.txt
* Downgrade typing-extensions back to 3.7.4.3 and remove Typeguard.
Typing-extensions 3.10.0.0 keeps giving problems even after the requirements.txt updated. Its been out for 3 months, but installing from Testpypi says it doesnt exist (have to install it manually first), and lots of libraries are still fixed to 3.7.4.x (including tensorflow and VScode's restructured text linter?!)
I've commented out all the function defs that use Typeguard, so they can be put back once the world updates. In the meantime, i replaced them all with 'cast' to keep mypy happy.
* Added more complex typing to BaseIndexEntry, SectionConstraint, GitConfigParser, _OMD.
* Rmved with_metaclass shim, not needed for python 3.
* Already includes the changes from previous PR that fixed the py.typed issue in setup.py. …
> Revert use of Typeguard and therefore typing-extensions==3.10.0.0

- git/repo/base.py
After creating a `Head` via `Head.create_head()`, mypy complains if I try to do head-like things with it:
```
error: "SymbolicReference" has no attribute "checkout"  
error: "SymbolicReference" has no attribute "set_tracking_branch"
```
> Fix typing of Head.create_head

- git/config.py
- git/objects/util.py
- git/refs/head.py
- git/refs/reference.py
- git/refs/tag.py
- git/repo/base.py
- test/test_refs.py
split # 1301,
merge while CI working
> Fix orderdict, improve types

- .flake8
- test-requirements.txt
The idea to include this plugin comes from #1095 . In short, flake8-typing-imports checks if a import from `typing` is possible in a certain python version.
I ran the plugin in your code base, and it's **NOT** compatible with <= 3.6.2. You use NamingTuple with defaults and NoReturn which were added in later patches of 3.6. To let in still run I set the minimum version to 3.7.0.
This means, that either we should fix the issues or gitpython needs to drop the support for this version which is anyway deprecated.
This plugin will hopefully prevent that any new issues are added
> Add flake8-typing-imports

- git/config.py
CI fails on master due to extra whitespace. The annotation is also incorrect, as if "1" is read from the config it will be converted to an integer, not a string.
> Fix trailing whitespace and incorrect overload

- git/config.py
- git/util.py
- test/test_util.py
On systems without any environment variables (such as sandboxed CI runs) and no `pwd` module (such as windows), GitPython crashes.
This is just a logic error - there is no reason to fallback to `pwd` until the config lookup has actually failed. The implementation of `ConfigWriter.get_value` is to catch `Exception`, so this patch doesn't attempt to work out a more specific exception than what was used before.
This fixes #356
> Do not call get_user_id if it is not needed

- git/repo/base.py
Allow the GitCommandWrapperType definition to be used within the Repo
classmethods. This change follows the intended purpose as stated in
the code, "Subclasses may easily bring in their own custom types by
placing a constructor or type here."
The usecase that prompted this change has to do with
`GIT_SSH_COMMAND`. The goal is to setup a custom `Git` class with
knowledge of the value, something like as follows
```python
from git import Git as BaseGit, Repo as BaseRepo
class Git(BaseGit):
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
self.update_environment(GIT_SSH_COMMAND=current_app.config['GIT_SSH_COMMAND'])
class Repo(BaseRepo):
GitCommandWrapperType = _Git
```
With this change, the above example will allow the developer to use
`Repo.clone_from(...)` with the …
> Use the Git class type definition within Repo classmethods

- git/remote.py
Fix encoding error:
```
UnicodeEncodeError: 'charmap' codec can't encode characters in position 39230-39231: character maps to <undefined>
```
> Add encoding to utf-8 for fetch_info_lines, for fetch_head_info;

- setup.py
> Import README.md into setup.py

- git/cmd.py
- git/remote.py
- test/test_remote.py
(hopefully) closes #1339 
This PR does as of  e058c4c  :
- renames `timeout` to `kill_after_timeout` and set default to `None` instead of `10 s`
- Surfaces `kill_after_timeout` to user facing functions (`remote. pull/push/fetch`)
- refactor `AutoInterrupt` so we can `._terminate()` the underlying process and grab status codes from terminated processes
- Add a class variable `AutoInterrupt._status_code_if_terminate`; if non-zero it overrides any status code from the process in `_terminate`. This can be used to prevent race conditions in tests, [as described in this comment](https://github.com/gitpython-developers/GitPython/pull/1340#issuecomment-919148742)
Some history of the commits (while trying a different strategy):
aafb300 changes the default timeout to 60 s
1d26515 allows `push`, …
> Surface fetch/pull/push kill_after_timeout and reset default to None

- git/refs/head.py
- git/refs/remote.py
- git/remote.py
- git/repo/base.py
delete_head and Head.delete historically accept either Head objects
or a str name of a head.  Adjust the typing to match.
Using assignment to make add an alias for create unfortunately
confuses mypy, since it loses track of the fact that it's a
classmethod and starts treating it like a staticmethod.  Replace
with a stub wrapper instead.
> Fix typing issues with delete_head and Remote.add

- git/__init__.py
- git/exc.py
- git/index/__init__.py
- git/objects/__init__.py
- git/refs/__init__.py
- test/lib/__init__.py
All `from <module> import *` has now been replaced by
`from <module> import X, Y, ...`.
Contributes to #1349
> Replace wildcard imports with concrete imports

- git/__init__.py
- git/exc.py
- git/index/__init__.py
- git/objects/__init__.py
- git/refs/__init__.py
- test/lib/__init__.py
This reverts commit 53d94b8091b36847bb9e495c76bb5a3ec2a2fdb5.
The reason for the revert is that the commit in question introduced a
regression where certain modules, functions and classes that were
exposed before were no longer exposed.
See https://github.com/gitpython-developers/GitPython/pull/1352#issuecomment-932757204
for additional information.
> Revert "Replace wildcard imports with concrete imports"

- doc/requirements.txt
Sphinx 4.3.0 has been released: https://github.com/sphinx-doc/sphinx/issues/9824#issuecomment-965571726
So we can remove the workaround from https://github.com/gitpython-developers/GitPython/pull/1361.
> Remove Sphinx workaround

- git/remote.py
- test/test_docs.py
- test/test_remote.py
List-like, so that it's backward compatible. But it has a new method
raise_on_error, that throws an exception if anything failed to push.
Related to #621
This is more of a proposal for this design. Is this actually backward-compatible? Should we check the flags of all PushInfos in `raise_on_error`? Is this better than a new method `push_really_or_else_raise()` or `push(raise=True)`? What if a `PushInfo` is missing from the result because it totally failed?
> Let remote.push return a PushInfoList

- requirements.txt
The original change requiring py3.10 TypeGuard (and matching
typing_extensions) has been reverted, so revert the requirement
on typing_extensions as well.
> Revert the use of typing_extensions in py3.8+

- .github/workflows/pythonpackage.yml
- git/index/base.py
This isn't needed as git will replace this file atomicially,
hence we always see a fully written file when reading.
Only when writing we need to obtain a lock.
Fixes #1388
> Avoid taking a lock for reading (#1388)

- git/diff.py
Use NUL character instead of semicolon to extract meta and path. Avoid errors in during git diff when dealing with filenames containing semicolons
> Use NUL character to extract meta and path from git diff

- git/objects/commit.py
Simple errors in the API documentation. Checked locally by `make html`
> Fix doc string error in Objects.Commit

- git/objects/submodule/base.py
- git/util.py
This should not be imported at root level, since it adds a lot of initialization overhead without need.
> import unittest adds 0.250s to script launch time

- git/index/fun.py
- test/test_index.py
Fix #971. Partly resolve #703.
If the hook doesn't have a file extension, then Windows won't know how
to run it and you'll get "[WinError 193] %1 is not a valid Win32
application". It's very likely that it's a shell script of some kind, so
use bash.exe (commonly installed via Windows Subsystem for Linux). We
don't want to run all hooks with bash because they could be .bat files.
test_index.py passes (two are skipped).
> Use bash to open extensionless hooks on windows

- git/cmd.py
To create a window application with pyinstaller, all suprocess input and output streams must be assigned and must not be None.
https://stackoverflow.com/a/51706087/7076612
> set unassigned stdin to improve pyinstaller compatibility

- git/repo/base.py
Pretty simple contribution: fix the comment description of the paths param which is currently wrong. 
Original description of what paths does confused me when I was reading through code, this should make it clearer and more in-line with the description in iter_items.
> fix iter_commits comment, more in line with iter_items

- git/refs/symbolic.py
Have faced the issue when trying to set a reference to a branch with non-ASCII symbols in the path. [Snippet](<https://github.com/openvinotoolkit/cvat/blob/dd60b2d8e0693772bc637b99a4f6684df887de30/cvat/apps/dataset_repo/dataset_repo.py#L131>).  I guess, this fix would resolve it.
> Fixed setting ref with non-ascii in path

- git/repo/base.py
This propagates the type of `Head.create`'s `reference` argument. That `create` function is inherited from `SymbolicReference`.
Mypy doesn't pass on my machine, but as far as I can see it reports no new errors compared to the CI runs on the main branch.
> Allow `Repo.create_head`'s `commit` arg to be a `SymbolicReference`

- AUTHORS
- git/cmd.py
- test/test_repo.py
This PR adds the `strip_newline` flag to the `Git.execute` method. When this flag is set to `True`, it will trim the trailing `\n`. The default value is `True` for backward compatibility. Setting it to `False` is helpful for, e.g., the `git show` output, especially with the binary file, as the missing `\n` may invalidate the file.
Looking at the first some bytes and checking if the output is binary or not is another option to prevent making an invalid binary file. Still, I chose to add a parameter because it is easy to implement, is fully backward compatible, and doesn't add many lines to the source code.
Fixes: #1377
By the way, do we need to handle stderr too?
> feat(cmd): add the `strip_newline` flag

- git/exc.py
- git/util.py
- test/test_exc.py
- test/test_util.py
Fixes #1284 
- Extend `remove_password_if_present` to remove usernames from URLs as well as the existing behavior of removing passwords from URLs.
- As an extra level of caution, I extended `CommandError.__init__` to also call `remove_password_if_present` just in case an exception gets raised from a non-sanitized command by mistake.
- Add test coverage for both of the above changes.
> Strip usernames from URLs as well as passwords

- doc/source/changes.rst
- git/config.py
- git/index/base.py
- git/index/fun.py
- git/objects/base.py
- git/objects/commit.py
- git/objects/submodule/root.py
- git/objects/util.py
- git/refs/symbolic.py
- git/refs/tag.py
- git/repo/base.py
- git/repo/fun.py
- git/types.py
- pyproject.toml
- test/fixtures/diff_p
- test/fixtures/git_config
- test/fixtures/rev_list_bisect_all
- test/test_config.py
- test/test_diff.py
- test/test_docs.py
- test/test_git.py
- test/test_index.py
- test/test_submodule.py
Found via `codespell -q 3 -S ./git/ext/gitdb,./test/fixtures/reflog_master,./test/fixtures/diff_mode_only,./test/fixtures/reflog_HEAD`
> Fix various typos

- git/index/base.py
- test/test_index.py
Close #1382
Apart from the automatic linting, relevant lines are [here](https://github.com/rdbisme/GitPython/blob/index-pathlike/git/index/base.py#L587-L591) + the additional test
> fix: Allow adding PathLike object to index

- .github/workflows/pythonpackage.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- .github/workflows/cygwin-test.yml
- git/repo/base.py
- git/repo/fun.py
- git/util.py
- test/test_docs.py
- test/test_repo.py
- test/test_submodule.py
It looks like the Cygwin CI testing was disabled a while back, possibly as part of the move to GHA.  I added a separate Cygwin CI run to the GitHub actions and tried to get the tests passing.  I have three test failures left that I don't understand, and hope someone here knows what's going on.
I can move the test to a separate step in the existing GHA workflow if that would work better in this project, or move it to a separate PR to wait for the last three tests to pass while the other fixes go in.
> Re-enable Cygwin CI and get most tests passing

- git/refs/tag.py
- test/test_refs.py
Previously if you passed the `message` kwarg, that would cause a `--message` argument to `git tag`, but then the code also added a `-m`, which caused the message to appear in the tag twice. Fix that by deleting `message` from the kwargs if we set `-m`.
> Fix bug in TagReference.create that would duplicate the message

- git/index/base.py
- git/index/typ.py
- test/test_blob_filter.py
Fix the types and type annotations of some of the blob filter code.
> Fix blob filter types

- git/cmd.py
gevent.monkey.patch_all() patches stderr to be gevent._fileobjectcommon._ClosedIO object, which raises its own FileObjectClosed(IOError).
This PR robustly handles OSError which IOError / FileObjectClosed error inherits from.
Fixes #1336
> Catch OSError to handle gevent monkey patching errors

- AUTHORS
- git/types.py
This adds a more rich type hinting for the `git.types.PathLike` class.
Closes #1473.
Also remove unused imports in this file.
> Fix incomplete typehinting for PathLike

- AUTHORS
- git/repo/base.py
related to: [#1479 ](https://github.com/gitpython-developers/GitPython/issues/1479)
this PR adds a `TypeError`-hint to the documentation in case the HEAD is detached and used in the `active_branch` of the `Repo` class.
This will help users to understand that there's no error on their side.
> Improve docs 

- AUTHORS
- git/config.py
- git/objects/commit.py
- test/test_commit.py
- test/test_util.py
Add co_authors property to the Commit object, which parses the commit message for designated co-authors, include a simple test.
> Add commit co-authors support

- AUTHORS
- git/repo/base.py
- test/test_repo.py
The `git blame` CLI offers a repeated `-C` option that can be used to detect
lines that move within/between files. While a slower operation, it yields more
accurate authorship reports.
https://git-scm.com/docs/git-blame#Documentation/git-blame.txt--Cltnumgt
While GitPython does enable passing custom kwargs to the command line `git`
invocation, the fact that kwargs is a dictionary (i.e. no duplicate keys) means
that there was no way to request the `-C` option in `git blame` more than once.
This commit adds an optional `rev_opts` parameter to the `blame` method which
accepts a list of strings to propagate to the CLI invocation of `git blame`. By
using a `List[str]` for `rev_opts`, users of GitPython can pass now the `-C`
option multiple times to get more detailed authorship reports from …
> feat(blame): Support custom `rev_opts` for blame

- git/diff.py
- test/test_diff.py
This commit introduces a potential fix for #1490 and #1483, in which an `invalid literal for int() with base 10: 'n'` exception was raised within a diff operation. Within `_handle_diff_line()`, we split the output of `git diff-tree` on colons (`:` characters), under the assumption that there are no colons within the paths of the files being diffed. On POSIX systems this is not a valid assumption. The fix is to split on `\x00:`, since a null character always precedes the colons we actually need to split on.
A test already existed for this case (`test_diff_file_with_colon()`), but it was marked as skipped.
* Split on `\x00:` instead of `:` in `_handle_diff_line()`.
* Unskip `test_diff_file_with_colon()`.
> Fix bug where colons in paths raise a `ValueError` on `diff()` calls.

- git/diff.py
- test/test_diff.py
In some cases, the git diff command does not return any output, this results in an exception in the diff line handling code.
```
File "../lib/python3.8/site-packages/git/diff.py", line 502, in _handle_diff_line
old_mode, new_mode, a_blob_id, b_blob_id, _change_type = meta.split(None, 4)
ValueError: not enough values to unpack (expected 5, got 1)
```
This fix ignores empty diff lines.
> Ignore empty info in diff line

- git/index/base.py
- git/objects/commit.py
Update type hints to match acceptable date types.
Passing a `datetime.datetime` object for `author_date` or `commit_date` causes a mypy type error, these dates are passed to `parse_date` in `git.objects.util`, which does accept a `datetime.datetime` object.
> Add datetime.datetime type to commit_date and author_date

- .github/workflows/pythonpackage.yml
- git/remote.py
- git/repo/base.py
- test/test_repo.py
Add `--` in some commands that receive user input
and if interpreted as options could lead to remote code execution (RCE).
There may be more commands that could benefit from `--` so the input is never interpreted as an option,
but most of those aren't dangerous.
Fixed commands:
- push
- pull
- fetch
- clone/clone_from and friends
- archive (not sure if this one can be exploited, but it doesn't hurt adding `--` :))
For anyone using GitPython and exposing any of the GitPython methods to users, make sure to always validate the input (like if starts with `--`). And for anyone allowing users to pass arbitrary options, be aware that some options may lead to RCE, like `--exc`, `--upload-pack`, `--receive-pack`, `--config` (https://github.com/gitpython-developers/GitPython/pull/1516).
Ref …
> Fix command injection

- git/remote.py
https://github.com/gitpython-developers/GitPython/pull/1360 was a great change, but it went undocumented, leading to [continued confusion](https://github.com/gitpython-developers/GitPython/issues/621#issuecomment-1093834110) about how to use the new feature.
This PR
* Adds docstring for `PushInfoList` so that it will show up in the API search index (currently it is [completely absent](https://gitpython.readthedocs.io/en/stable/search.html?q=PushInfoList&check_keywords=yes&area=default)).
* Changes type hint of the return value of `push` to match what is actually returned.
* Corrects the docstring for return value of `push`.
> Document PushInfoList

- git/repo/base.py
pycharm yells at me without this
> Fix type hint on create_tag

- AUTHORS
- git/cmd.py
- git/exc.py
- git/objects/submodule/base.py
- git/remote.py
- git/repo/base.py
- test/test_git.py
- test/test_remote.py
- test/test_repo.py
- test/test_submodule.py
This got a little longer than expected :face_exhaling:, there were other places where git accepted `ext::` URLs, like `git pull/push/fetch <URL>` https://git-scm.com/docs/git-remote-ext#_examples
And there are other config options that can be harmful, so I think we should just forbid the `--config` option, if anyone is relying on that option, they can opt-out with `allow_unsafe_options=True`.
`--*-pack` and `--exec` are the options that I found that could lead to RCE, but anyone allowing users to pass arbitrary options should be aware that it may be more of these, don't know.
This is still missing adding/updating tests.
This is on top of https://github.com/gitpython-developers/GitPython/pull/1516
Fixes https://github.com/gitpython-developers/GitPython/issues/1515
> Block insecure options and protocols by default

- git/cmd.py
- git/index/base.py
- git/index/fun.py
- git/objects/base.py
- git/objects/fun.py
- git/objects/tree.py
- git/objects/util.py
- git/refs/log.py
- git/refs/reference.py
- git/remote.py
- git/repo/base.py
- git/util.py
These errors are mostly fixed by either adding blank lines or single spaces for Sphinx documentation key words.
The PR solely includes documentation changes, no functional changes.
> Fix Sphinx rendering errors

- test/test_git.py
Use `command -v` to locate the git executable instead of `which`. The former is guaranteed to always be available according to POSIX, while which(1) is a redundant third-party tool that is slowly being phased out from Linux distributions.  In particular, Gentoo no longer installs it by default.
> tests: Use `command -v` instead of third-party `which` program

- test/test_remote.py
- test/test_repo.py
- test/test_submodule.py
* uses `tempfile.TemporaryDirectory()` instead of `tempfile.mkdtemp()` to not leave temporary files behind (though that still happens in some other tests that are harder to fix);
* fixes a typo (procol instead of protocol);
* replaces `/tmp/pwn` w/ `{tmp_file}`;
* clones into `tmp_dir / "repo"` instead of `tmp_dir`, since `tmp_dir / "pwn"` will never exist afterwards otherwise;
* adds a test w/ `ext::sh` that actually allows the protocol, to ensure we're not missing anything in the other tests.
> use tempfile.TemporaryDirectory & fix clone_from_unsafe_protocol tests

- git/objects/commit.py
- test/test_commit.py
GitPython parses the output of `git diff --no-renames` to get the files changed in a commit.
This breaks when a commit contains a file rename, because the output of `git diff` is different than expected.
This is the output of a normal commit:
```
$ git diff --numstat 6ab9810cfe6c^ 6ab9810cfe6c
5       2       drivers/clk/zynqmp/divider.c
```
And this a commit containing a rename:
```
$ git diff --numstat db401875f438^ db401875f438
1       1       tools/testing/selftests/drivers/net/mlxsw/{spectrum-2 => }/devlink_trap_tunnel_ipip6.sh
```
This can be triggered by this code:
```python
for commit in repo.iter_commits():
print(commit.hexsha)
for file in commit.stats.files:
print(file)
```
Which will print for the normal commit:
```
6ab9810cfe6c8f3d8b8750c827d7870abd3751b9 …
```
> fix files list on file rename

- .github/workflows/cygwin-test.yml
- .github/workflows/lint.yml
- .github/workflows/pythonpackage.yml
- .pre-commit-config.yaml
- README.md
- setup.py
- test-requirements.txt
Add the Trove classifier to declare support for Python 3.11 on PyPI.
Also a few other little changes to `setup.py`.
> Declare support for Python 3.11

- git/repo/base.py
- test/test_repo.py
* Add test to sanity-check basic behavior of `ignored()` method
* Add test to verify GitCommandError is raised if `git check-ignore` returns any error code other than 1
* Modify `ignred()` method to raise GitCommandError if `git check-ignore` returns any error code other than 1
> Fix ignored

- git/objects/util.py
- test/test_util.py
The `utctz_to_altz` and `altz_to_utctz_str` functions fail to handle timezones with UTC offsets that are not a multiple of one hour. Rewrite them and add some unit tests.
Fixes #630
> Fix timezone parsing functions for non-hour timezones

- git/diff.py
- test/test_diff.py
Small fix to allow overriding of default diff **-M** arg. Using --find-renames=<n> or -M<n> or --no-renames will disable **-M**.
Full discussion is here:
https://github.com/gitpython-developers/GitPython/discussions/1195
> Enable user to override default diff -M arg

- git/repo/base.py
- test/test_base.py
Neither `working_dir` nor `git_dir` appear to leave `__init__()` set to `None`. Let's remove the `None` initialization, and simply use them as type markers.
Fixes https://github.com/gitpython-developers/GitPython/issues/1549
> Remove optional from two member variables

- git/cmd.py
`next(self)` was previously just a recursive call that does nothing.
This now implements `__next__` using the actual implementation, and lets the python2-compatibility `next()` just wrap it.
> Fix RecursionError when iterating streams

- git/config.py
- test/test_config.py
As described in https://github.com/gitpython-developers/GitPython/issues/1534, some calls to GitConfigParser().get_values() fail in main with a `KeyError` about a missing section name even though the named sections do exist within the config file.
Add a test that calls get_values() before anything else to catch this failure. Update the get_values() function to work, even if it's the first call after creating the GitConfigParser, by eagerly load the section names before trying to access them. This passes the new test.
> Fix get_values() so it correctly loads section names

- git/objects/commit.py
- test/test_commit.py
Add trailers_dict and trailers_list methods to fix the commit trailers functionality.
I left the existing method as is to not break any existing code using it, leaving a comment about how it's incorrect.
Also updated the trailers tests.
Work here resolves issue https://github.com/gitpython-developers/GitPython/issues/1533
> Fix up the commit trailers functionality

- README.md
- setup.py
Hi,
I recently found this great project on PyPi and noticed the short description.
I understand that thats caused by the following. The `setup.py` file reads the `README.md` but then the variable `long_description` remains unused. Instead the string `"""GitPython is a ... repositories"""` is used as the value of the `long_description` attribute.
I also applied a few changes to the `README.md` to increase the readability of the code blocks.
Regards,  
Jean-Luc
> fix pypi long description

- git/repo/base.py
- test/test_repo.py
I'm part of the Debian LTS (Long Term Support) Team and I'm working on integrating the fix for CVE-2022-24439 for GitPython in Debian.
After contacting @Byron privately we determined that #1521 would need a follow-up fix, which I hereby propose in this PR.
I also modified 2 tests to validate the change, but I'm not sure if we want to double-check (multi/non-multi) all the currenttt clone/clone_from tests, so I didn't, but I can do so if necessary.
> Block insecure non-multi options in clone/clone_from

- doc/source/index.rst
- doc/source/quickstart.rst
- test/test_quick_doc.py
Hey, this PR is in reference to an [issue](https://github.com/gitpython-developers/GitPython/issues/1605) I raised. I would like to add a quick start guide to act as another resource for developers, I planned the guide to be mainly code snippets as opposed to a text based tutorial.
I finished all the code and section headers I planned to add to the quick doc. I still want to add a few short sentences to improve readability. The tutorials includes how to do basic repo operations like init, clone, add, commit and push. Also shows how to iterate through the trees and print a text file.
Where possible I tried to follow the conventions the regular tutorial followed (ie having the code snippets inside of the test file) but in some cases I had to add code directly to the RST (I did this to avoid …
> WIP Quick doc

- README.md
- git/__init__.py
- git/cmd.py
- git/config.py
- git/diff.py
- git/exc.py
- git/index/base.py
- git/index/fun.py
- git/objects/commit.py
- git/objects/fun.py
- git/objects/util.py
- git/remote.py
- git/repo/base.py
- git/util.py
- pyproject.toml
Some of the typing errors require deeper knowledge, so I was not able to fix them in reasonable time.
- Do not typecheck submodule
- Define supported version for mypy
- Ignore remaining [unreachable] type errors
- Allow explicit casting even when slightly redundant
- Run black and exclude submodule
- Add missing type annotation
- Apply straight-forward typing fixes
> Partial clean up wrt mypy and black

- git/repo/base.py
- test/test_refs.py
> Disable merge_includes in config writers

- git/cmd.py
- test/test_git.py
Fixes #1635
This fixes the path search bug where the current directory is included on Windows, by setting `NoDefaultCurrentDirectoryInExePath` for the caller. (Setting for the callee env would not work.)
This sets it only on Windows, only for the duration of the `Popen` call, and then automatically unsets it or restores its old value.
`NoDefaultCurrentDirectoryInExePath` is documented in [NeedCurrentDirectoryForExePathW function (processenv.h)](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-needcurrentdirectoryforexepathw). See also [this SO post by Mofi](https://stackoverflow.com/a/50118548/1038860).
It automatically affects the behavior of `subprocess.Popen` on Windows, due to the way `Popen` uses the Windows API. (In contrast, it does not, at least …
> Fix CVE-2023-40590

- git/util.py
Otherwise, this will leak file handles and can be a problem in Windows. Also, `closefd=true` is the default here, so no need to pass it explicitly.
Regression from #1619.
I noticed after [our tests started raising `ResourceWarning`][1] after 3.1.33 release.
```python
File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/git/util.py", line 938, in _obtain_lock_or_raise
open(lock_file, mode='w', closefd=True)
ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/pytest-of-runner/pytest-0/popen-gw0/external0/project.git/.git/config.lock' mode='w' encoding='UTF-8'>
```
[1]: https://github.com/iterative/dvc/actions/runs/6055520480/job/16434544764#step:6:869
> util: close lockfile after opening successfully

- git/objects/submodule/base.py
When a repository have a `.gitmodules` file and the actual path defined in the git repository is not related to submodule, GitPython still assumes its a submodule.
To replicate:
```bash
mkdir test
cd test
git init
mkdir DbConnector
touch DbConnector/readme.md
touch .gitmodules
git add .
git commit -m "test"
```
```ini
[submodule "DbConnector"]
path = DbConnector
url = https://github.com/chaconinc/DbConnector
```
Then in a python section
```python
from git.repo import Repo
r = Repo('.')
r.submodules
```
the following error occurs
```
In [3]: r.submodules
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 r.submodules
File …
```
> Fix 'Tree' object has no attribute '_name' when submodule path is normal path

- git/refs/symbolic.py
- test/test_refs.py
This change adds a check during reference resolving to see if the requested reference is inside the current repository folder. If it's ouside, it raises an exception.
This fixes [CVE-2023-41040](https://github.com/advisories/GHSA-cwvm-v4w8-q58c), which allows an attacker to access files outside the repository's directory.
This closes https://github.com/gitpython-developers/GitPython/issues/1638.
> Fix CVE-2023-41040

- .github/workflows/cygwin-test.yml
- .github/workflows/pythonpackage.yml
- test/test_submodule.py
Closes #1544
**Edit:** When making this PR, I didn't notice #1647, which was recently opened (but opened before this PR; #1647 came first). That PR includes an alternative to the approach taken here. It uses a GitPython feature to set `protocol.file.allow` in `git` command-like arguments, while this patches `GIT_CONFIG_*` environment variables. Both approaches are specific and, I believe, robust. The approach in this PR avoids using more GitPython features that are not conceptually under test in the submodule tests. But the approach in #1647 is significantly more compact, which might be considered the more important benefit. I will not mind if this is closed in preference for #1647! At this time, both #1647 and this PR also contain changes beyond those that directly address #1544, and …
> Only make config more permissive in tests that need it

- AUTHORS
- README.md
- test/test_submodule.py
Following from here: https://github.com/gitpython-developers/GitPython/pull/1645#issuecomment-1708908630, I've added a test in the corresponding position.
Meanwhile, I've noticed there are test failures related to [CVE-2022-39253](https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html). I did a quick fix in place by adding git configs in the Cmd.
Since I also had the chance to do a fresh start on testing, I updated the docs on where it was unclear to me and caused issues. Particularly, I highlighted that `git fetch --tags` should be ran first otherwise it would cause test failures regarding version `0.1.6` something something.
Each small change in clearly separated by commits, so if there is any …
> Added test for PR #1645 submodule path

- git/cmd.py
- git/util.py
- test/fixtures/env_case.py
- test/test_git.py
*This pull request might be ready, but it is still a draft because I think I should look it over once more for any serious problems.*
Fixes #1646
This fixes the bug I inadvertently introduced in #1636 where all environment variables' names are set upper-case on Windows.
It uses a simple hand-rolled context manager to patch the `NoDefaultCurrentDirectoryInExePath` variable, instead of `unittest.mock.patch.dict`. The latter was setting unrelated environment variables to the original (same) values via `os.environ`, and as a result, their names were all converted to upper-case on Windows. This is the intended behavior of `os.environ` on Windows, at least in CPython, per https://github.com/python/cpython/issues/73010 and https://github.com/python/cpython/issues/101754, but I had not been …
> Fix Windows environment variable upcasing bug

- git/util.py
- test/fixtures/env_case.py
- test/test_git.py
This improves how some of the changes in #1650 are documented, expanding comments and a docstring.
I ended up doing this in four commits, but really it would probably be just as clear with two. If you'd like me to rebase this to have just two commits, please let me know.
This is my main motivation for opening this PR, and most of the change.
I was thinking about how it was not immediately obvious why `test_it_avoids_upcasing_unrelated_environment_variable_names` (the "`env_case`" test) works and why it is done in this way.
To improve on this, I wrote comments that divide it into four steps. Two of the steps occur in the test case method, and the others occur in the supporting `env_case.py` fixture. The comments are in both files.
This only adds and changes comments, but just in case I …
> Better document env_case test/fixture and cwd

- .gitattributes
- .gitignore
- Makefile
- build-release.sh
- check-version.sh
Fixes #1660
In `.gitattributes`:
- Fix checking out `init-tests-after-clone.sh` with LF line endings on all systems (this was broken).
- Add `Makefile` to so it is also checked out with LF line endings on all systems.\
(Windows ports of `make` will usually tolerate CRLF line endings, but `\r` or other representations of CR may, and often do, appear in output, giving an appearance of a problem that is hard to dismiss. So it's worth keeping it LF.)
For the `force_release` target:
- Don't try to upload if building failed (#1660).
- Only suggest using a virtual environment to solve a failure that occurred outside of one.
- In a virtual environment, use `python`, not `python3`, for compatibility with Windows.\
(Windows may have a `python3` command installed outside the virtual environment, …
> Fix up checks in Makefile and make them portable

- AUTHORS
- CONTRIBUTING.md
- LICENSE
- README.md
This contains miscellaneous formatting fixes and minor proofreading in the top-level documentation files, plus making the text in the license section of `README.md` have links both to external information about the license and to the license file itself. The common theme is that these are changes to "documentation" files in the root of the repository that are individually minor but seem worth making and also don't seem like they would fit well in any other PR about anything else.
Note that the changes to the license file are just removal of excess whitespace (the extra blank line at the end, and spaces appearing at the end of lines). This does not attempt to change what license it used, *nor* the text of the license!
Some of are changes that are vaguely related to other PRs (whether …
> Assorted small fixes/improvements to root dir docs

- test-requirements.txt
- test/test_installation.py
This eliminates the test dependency on `virtualenv` by using the standard library `venv` module instead in `test_installation`.
This is independent of which, if either, users use for the environment that the test runner is run in. `sys.executable` is the Python interpreter of that environment, but once he test creates the virtual environment, it uses the virtual environment's `python` and `pip` commands for everything else. This is really the same exact approach as before, just instead of installing `virtualenv` as a dependency of the project, the standard library `venv` is used.
`venv` is more commonly used and more widely recommended today than `virtualenv`. So while users can use either and they both work well, it makes sense to test with venv instead. It is rare but possible for a …
> Use venv instead of virtualenv in test_installation

- setup.py
This removes the `py_modules` keyword argument in the call to `setup`, and further shortens/simplifies `setup.py` by removing the newly unused `build_py_modules` function.
The `packages` keyword argument already covers this, because we have no loose modules that are included in the distribution, and the call to `find_packages`:
- Omits everything in `test/` because it is directed to do so in the call.
- Omits the `gitdb/` directory (currently existing as a git submodule, not to be confused with Python submodules). This is because the `ext/` directory that contains it does not itself directly contain an `__init__.py` file, so `ext/` is not a traditional package, yet `ext/` is contained and found inside the directory `git/` that *is* a traditional package, so the `ext/` directory is not a …
> Omit py_modules in setup

- .gitignore
While running tests with coverage enabled (as is automatically the case in this project), files of the form `.coverage.MachineName.####.######` are created temporarily. For example, on my system, one of the names was recently `.coverage.Glub.7791.638878`.
When tests complete normally (whether or not there are failures), these files are automatically removed. However, when tests are cancelled with SIGINT (<kbd>Ctrl</kbd>+<kbd>C</kbd>), they are sometimes retained.
This adds another pattern to `.gitignore` so that, in addition to not tracking the `.coverage` file that is retained after tests, these other temporary files are also not tracked.
Further considerations:
- This also has the benefit of avoiding a situation at development time where one runs tests and also stages deliberate code …
> Don't track code coverage temporary files

- .gitignore
- requirements-dev.txt
- tox.ini
This adds a `tox.ini` file so that `tox` can be run locally to test on 3.7, 3.8, 3.9, 3.10, 3.11, and 3.12, or whichever of them are available, and also run the lint, formatting, and style checks.
Because CI also tests building the documentation, and it is convenient to be able to use `tox` to check all the things CI checks (albeit on just one's local platform), I have added a tox environment for that too. But because it actually writes to the build directory, I have not listed it in `env_list` at the top, so it doesn't run automatically--it can still be run with `tox -e html`. That could be improved in the future, but I think reasonable ways of doing so would involve modifying `doc/Makefile` to make it more configurable, and that seems outside the proper scope of this PR.
**This PR does …
> Configure tox

- README.md
- pyproject.toml
- test/performance/test_streams.py
- test/test_commit.py
- test/test_diff.py
- test/test_docs.py
- test/test_index.py
- test/test_quick_doc.py
- test/test_repo.py
- test/test_submodule.py
- test/test_util.py
- tox.ini
This expands the use of `black` to cover the whole codebase (still excluding submodules).
- Replaced `exclude` with `extend-exclude` so `black`'s default exclusions, which include anything specified in `.gitignore`, remain in effect as well as the specific path(s) specified to be excluded. This allows `black .` to be run to format everything that should be formatted and nothing that shouldn't.
- Made a few manual formatting adjustments that lead to more readable code in a few places once formatted with `black`. (This does not have to be redone; the idea is to be in the common subset of what was intended and what `black` considers its style.)
- Changed `black git` to `black .` in the instructions in `README.md` and in the command in `tox.ini` that runs via `tox` or `tox -e black`.
- …
> Format tests with black and auto-exclude untracked paths

- .flake8
- .pre-commit-config.yaml
- git/objects/submodule/base.py
- git/refs/log.py
- git/repo/base.py
- git/util.py
- test/lib/helper.py
- test/test_commit.py
- test/test_diff.py
- test/test_docs.py
- test/test_git.py
- test/test_quick_doc.py
- test/test_remote.py
- test/test_repo.py
- test/test_submodule.py
Fixes #1670
Fixes #1671
I've upgraded `flake8` in the pre-commit configuration, which automatically upgrades its `pycodestyle` dependency. This makes it compatible with Python 3.12 (or at least we seem unaffected by any remaining incompatibilities). I've also upgraded its non-default plugins, which are listed there as additional dependencies. I have fixed a warning that was for some reason specific to 3.12 about spacing around `+`, as well as some new warnings that came in the new version of `pycodestyle` and new versions of the non-default packages. This included changing `==` to `is` and `!=` to `is not` when comparing `type` objects, since in all cases it appeared *exact* type matching was intended (rather than what an `issubclass` or, under simplification of the surrounding code, …
> Upgrade and broaden flake8, fixing style problems and bugs

- git/config.py
- git/index/base.py
- git/refs/log.py
- git/refs/symbolic.py
Fixes #1669
This fixes the *specific* bug in `SymbolicReference.set_reference` where the local call to `ldf.rollback` is never made. It also refactors, both here and elsewhere, to make `try`-`finally` logic clearer and simpler, and in some cases to replace it. This is to prevent such bugs from recurring, or at least make them easier to spot. This cleanup corresponds to `try`-`finally` cleanup done in the test suite as part of the larger PR #1673, but none of these changes were necessary to fix `flake8` warnings, nor directly related to changes that were necessary for that, and it seemed like including this in that PR would make it broader than would be ideal.
As noted in https://github.com/gitpython-developers/GitPython/issues/1669#issuecomment-1729125356, the best solution to this, along …
> Fix rollback bug in SymbolicReference.set_reference

- test/test_docs.py
- test/test_refs.py
- test/test_submodule.py
Fixes #1674
Along with removing all `@NoEffect` annotations (there were only a handful), this:
- Adds missing asserts, where an expression statement was by itself that was intended as an assertion. This turned out to be the case in the places `@NoEffect` appeared in rendered documentation, making it so no per-file-ignores or other broadened suppressions were needed.
- Fixes misspellings (including one case affecting documentation).
- Adds a FIXME comment for investigating a free-standing expression statement with no obvious side effects that may have been meant as an assertion but [would fail if turned into one](https://gist.github.com/EliahKagan/9c49ca00036b3138458cbbfd0c008ebc).
There are some other commented `@`-style suppression annotations throughout the project. This PR deliberately …
> Remove `@NoEffect` annotations

- git/refs/symbolic.py
- test/test_refs.py
This change adds checks based on the rules described in [the docs] in order to more robustly check a refname's validity.
[the docs]: https://git-scm.com/docs/git-check-ref-format
> Add more checks for the validity of refnames

- test/test_submodule.py
This turns two tuple expression statements--each of an equality comparison and message--that were not being checked or otherwise used, and that were intended to be assertions, into assertions.
> Add missing assert keywords

- .github/workflows/cygwin-test.yml
- .github/workflows/lint.yml
- .github/workflows/pythonpackage.yml
- pyproject.toml
- test-requirements.txt
- test/test_base.py
- test/test_config.py
- test/test_fun.py
- test/test_index.py
- test/test_repo.py
- test/test_submodule.py
- test/test_tree.py
- test/test_util.py
This makes changes so tests give more informative output, both locally and on CI but especially on CI. It comprises several interrelated changes that should help lead up to, but *do not include*, adding CI jobs for Windows. My motivation for doing this was to make it easier to add those jobs, and to get the most out of those jobs once they are added, but it seems to me that the benefit of these changes is actually largely independent of those goals, and can be reviewed independently of them (and thus before they are done). This description is divided into descriptions of the problems I believe the changes solve, and how they solve them.
The [`pytest-sugar`](https://github.com/Teemu/pytest-sugar/) plugin is working very well for local testing, but on CI it has been producing output that is …
> Make clear every test's status in every CI run

- README.md
In #1663, I linked from the readme to the license file, except I accidentally combined two styles of Markdown links in a way that doesn't actually work, and the link is a 404. This affected only the link to the license file *in* the repo, not to the external page about the license. I'm not sure how I missed this, but my guess is that I tested it using a case-insensitive filesystem, on which the link would incidentally have worked. (It does not work when browsing GitHub, so this PR is fixing a documentation bug.)
> Fix new link to license in readme

- .flake8
- .pre-commit-config.yaml
Some `flake8` suppressions are no longer needed and can be removed even without changing any Python code. This PR removes them, as well as the comments that were present to explain them. Other comments are retained. I've also reformatted the pre-commit and flake8-specific configuration files for readability.
In #1673 I mentioned I didn't plan to do anything more with `flake8` before trying to replace it with `ruff`, but I realized that these changes make the configuration simpler and shorter. (They *may* also make a switch to `ruff`, if/when it is done, easier, because there are fewer suppression to look up how to do. But I am not asking that this PR be evaluated on that basis.)
> Drop unneeded flake8 suppressions

- README.md
- test/lib/helper.py
On a current Cygwin system with git 2.39.0 (the latest version offered by the Cygwin package manager), `git-daemon` is present, with the Cygwin path `/usr/libexec/git-core/git-daemon.exe`. I believe this has been the case for a long time; as detailed below, Cygwin was not ever treated specially in the way that was assumed, yet no breakage resulted.
The `cygwin-test.yml` workflow does not take any special steps to allow `git-daemon` to work, but all tests have been passing in it even without skipping or xfailing tests that seem related to `git-daemon`.
The `git_daemon_launched` function in `test/lib/helper.py` invokes `git-daemon` directly (rather than through `git daemon`) only when `is_win` evaluates true. This only happens on native Windows systems, while Cygwin is treated the same as …
> Update instructions and test helpers for git-daemon

- git/cmd.py
- test-requirements.txt
- test/test_git.py
Fixes #1685
Fixes #1686
This updates the `shell` variable itself, only when it is `None`, from `self.USE_SHELL`.
(That attribute usually gets its value from `Git.USE_SHELL` rather than being separately instance attribute. But `self.USE_SHELL` is an idiomatic way to access it. Furthermore, although people probably shouldn't set it on instances, people may expect that this is permitted.)
Now:
- `USE_SHELL` is used as a fallback only. When `shell=False` is passed, `USE_SHELL` is no longer consulted. Thus `shell=False` always keeps a shell from being used, even in the non-default case where the `USE_SHELL` attribute has been set to `True`.
- The debug message printed to the log shows the actual value that is being passed to `Popen`, because the updated shell variable is used both to produce …
> Fix Git.execute shell use and reporting bugs

- .github/workflows/pythonpackage.yml
Since 3.12.0 stable has been released, and is [available via setup-python](https://github.com/actions/python-versions/blob/main/versions-manifest.json).
This is not needed to cause setup-python to select the stable version, so long as nothing goes wrong. However, I believe that unexpected version unavailability, or (more likely) the future *presence* of a prerelease of a patch version, could cause a prerelease to be wrongly used. Furthermore, because it would be incorrect for a prerelease to be used for 3.12 from this point forward, and because 3.12 is no longer differently situated from other Python releases with respect to the suitability of prerelease versions, the workflow should no longer explicitly state that a prerelease is acceptable for 3.12.
I've kept the machinery for marking a …
> No longer allow CI to select a prerelease for 3.12

- git/cmd.py
- test/test_git.py
This is a sequel to #1687, improving how parameters to `Git.execute` are documented, and improving debug logging and tests of how they affect the arguments passed to `Popen`.
In the `Git.execute` docstring, the method is no longer described as using a shell, since this is typically (and by default) not the case; the items documenting each parameter are listed in the order of the parameters; and some copyediting is done, for clarity, consistency, spacing, and in a few cases other formatting. I copyedited some other docstrings in the module as well.
The order of names in the `execute_kwargs` set is tweaked to also match the order in which they appear as parameters to `Git.execute`. (This is just for the purpose of code clarity, as `set` objects guarantee no particular iteration order.) …
> Clarify Git.execute and Popen arguments

- .github/dependabot.yml
- .github/workflows/cygwin-test.yml
- .github/workflows/lint.yml
- .github/workflows/pythonpackage.yml
- .pre-commit-config.yaml
- Makefile
- README.md
- build-release.sh
- check-version.sh
- doc/Makefile
- init-tests-after-clone.sh
- test/test_git.py
- tox.ini
Fixes #1690
Fixes #1691
Fixes #1692
This combines the solutions I recommended in those three issues on a single branch. Although I feel this does compose into a coherent whole, with each of those issues' practical ramifications having some tendrils into each other, and opening separate PRs would have resulted in nontrivial merge conflicts... nonetheless this PR is broader than I would usually like. But I have done it this way because it was by working on them together that I was able to get clear on the distinct ideas that I presented as those issues, as well as whether the solutions would work reasonably when all combined.
This PR is what remains after pieces that seemed reasonable to sever into their on PRs, such as #1684, have been removed, and excessively enterprising ideas, such as …
> Improve scripts and tool configurations

- README.md
- test/lib/helper.py
This changes the test helpers on Windows to use `git --exec-path` (with whatever `git` GitPython is using) to find the directory that contains `git-daemon.exe`, instead of finding `git-daemon.exe` in a PATH search.
Because it is only on Windows that the tests run `git-daemon` directly rather than using `git daemon`, this only affects Windows. Note that this does *not* affect Cygwin, which like other Unix-like systems uses `git daemon` for the tests.
This change has three benefits:
- **The documentation is shortened and simplified**, because the part on how to get `git-daemon` working on Windows is removed.
- **The effort required to set up GitPython for testing is reduced** because that no longer has to be done (but see below).
- **Users will not be tempted to put Git's `libexec\git-core` …
> Ask git where its daemon is and use that

- git/objects/submodule/base.py
- git/util.py
- test-requirements.txt
- test/test_docs.py
- test/test_submodule.py
- test/test_util.py
Fixes #1698
Fixes #1699
*May* close #1571
This takes the approaches I suggested in #1698 and #1699 for those two issues. It also adds tests for both the already-working behavior and the new behavior. For the tests of new behavior, I have manually verified they failed in the expected way, and now pass, on native Windows. (Other results can be seen on CI.)
For interpreting the `HIDE_WINDOWS_KNOWN_ERRORS` and `HIDE_WINDOWS_FREEZE_ERRORS` environment variables:
- I have kept `True` as the default (though we may be able to change that in the near future, even before fully addressing #790).
- `0`, `false`, and `no`, as well as the empty string, are treated as `False`. This is case-insensitive and ignoring leading and trailing whitespace.
- While other values are currently treated as `True`, …
> Fix bugs affecting exception wrapping in rmtree callback

- git/exc.py
When #1659 was updated to pick up linting configuration changes, it inadvertently undid one of the URL changes made in #1662, putting the URL in the `git.exc` module back to the one that redirects to a different BSD license from the one this project uses.
Since only that one module was affected, the fix is simple. This only changes the URL back; it doesn't undo any other #1659 changes.
> Fix small #1662 regression due to #1659

- SECURITY.md
Versions may still be yanked for security reasons under specific circumstances, but this is not the usual or most common practice in GitPython, at least currently. Recent security updates have not been accompanied by yanking older versions, and allowing these versions to be selected automatically even when not called for specifically can be good, such as to prevent an even older version with even more vulnerabilities from being selected in situations where for some reason the latest version cannot yet be used.
In general, users shouldn't (and don't) assume all non-yanked versions to be free of security fixes that later versions have received. This change updates SECURITY.md to avoid giving that impression, but of course some versions of GitPython may still be yanked in the future if …
> Drop obsolete info on yanking from security policy

- .github/dependabot.yml
This extends the current Dependabot configuration so that, in addition to offering updates for GitHub Actions, it also offers them for git submodules (for the gitdb direct submodule).
This is to make updating the gitdb submodule more convenient, as well as making the its *intended* status relative to the head of gitdb clearer:
- PRs are set to be created monthly, or less often if the head of the gitdb repository has not advanced.
- They can also be triggered manually, so having them set monthly should never hold anything back.
- This proposal is *not* based on the idea that GitPython should always be kept up to date with gitdb. Dependabot PRs can be closed, and this signifies both to Dependabot *and to humans* that the specific update the Depedabot PR was for is not wanted at this time. …
> Have Dependabot offer submodule updates

- README.md
This updates the release-making instructions in the readme, to release without using milestones and to link to the GitHub release page rather than a milestone, as discussed in #1706.
I've also made those instructions a numbered list, since they consist of sequential steps, and decreased the amount of elaboration in one of the other steps, which I think will make it so the new important details in the changelog-writing step are less likely to be glossed over.
In addition to the changes here, `check-version.sh` could and, I think, should be extended to check that the top section in `changes.rst` properly links to the (forthcoming) release page on GitHub. That link contains the version number (rather than a milestone number) so it makes sense for the version check script to validate it. …
> Update readme for milestone-less releasing

- .github/workflows/cygwin-test.yml
This passes `--login` to the `bash` shell used to run commands in the Cygwin environment on CI. This eliminates the need to work around a partly broken environment, and the extra code what was used to do that is accordingly removed. There are two benefits of this change:
- The `PATH` is correct: Cygwin's `/usr/local/bin` and `/usr/bin` are present at the beginning of `PATH`. Otherwise, it is easy to get `/usr/bin` at the front, but rather involved to get `/usr/local/bin` to precede it. Because Python on Cygwin puts scripts/executables such as the upgraded `pip` and the `pytest` command in `/usr/local/bin`, it is valuable to have that directory in the `PATH` and best to have it before `/usr/bin`. (I have set `CYGWIN_NOWINPATH` to omit other directories, since finding any of the commands to …
> Run Cygwin CI workflow commands in login shells

- git/__init__.py
- git/db.py
- git/exc.py
Fixes #1718
This adds `__all__` in `git.exc`, and adjusts `__init__.py` imports.
The `git.exc` module imports exceptions from `gitdb.exc` to republish them, as well as defining its own (also for use from outside). But because it did not define `__all__`, the intent for the exceptions it imported was unclear, since names that are introduced by imports and not present in `__all__` are not generally considered public, even when `__all__` is absent and a `*` import would reimport them.
This rectifies that by adding `__all__` and listing both imported and newly introduced exceptions explicitly in it. Although this strictly expands which names are public under typical conventions, it strictly contracts which names are imported by a `*` import, because the presence of `__all__` suppresses names …
> Add `__all__` in git.exc

- .github/dependabot.yml
This sets the Dependabot submodule update cadence from montly to weekly, as requested in https://github.com/gitpython-developers/GitPython/pull/1702#issuecomment-1761182333.
This change in GitPython corresponds directly to [#104](https://github.com/gitpython-developers/gitdb/pull/104) in gitdb. Just as there, I'm opening this PR separately from others so it can be merged at whatever point is most convenient, regardless of if and when other pull requests are merged.
> Set submodule update cadence to weekly

- git/cmd.py
- git/config.py
- git/db.py
- git/exc.py
- git/index/base.py
- git/objects/base.py
- git/objects/commit.py
- git/objects/submodule/base.py
- git/objects/submodule/root.py
- git/objects/submodule/util.py
- git/objects/tag.py
- git/objects/tree.py
- git/objects/util.py
- git/refs/head.py
- git/refs/log.py
- git/refs/reference.py
- git/refs/remote.py
- git/refs/symbolic.py
- git/remote.py
- git/util.py
- test/performance/lib.py
- test/test_commit.py
- test/test_git.py
- test/test_index.py
- test/test_remote.py
This replaces 2-argument `super(...)` calls with the zero-argument `super()` form everywhere applicable:
- All uses of two-argument `super` in the *code* are replaced.
- All but one mention of two-argument `super` in *comments* are replaced.
I had omitted this from #1725 because it may require more technical attention to fully check than other code changes there, and that PR was mostly for comments and docstrings.
*Since `super` is in practice one of the most confusing features of Python, I've included this section to help in verifying the changes here, and also so that they could be reverified later. However, this section is optional.*
As noted in output of `help(super)` (which is from [this code](https://github.com/python/cpython/blob/f4b5588bde656d8ad048b66a0be4cb5131f0d83f/Objects/type …
> Use zero-argument super()

- git/refs/symbolic.py
This removes a comment noting that a `try`-`finally` block had been present (or had been intended), but was removed because some version of Python had imposed a limitation on yield appearing in `try`-`finally`.
That comment was obsolete as of 58c5b99 (#326), which wrapped the relevant code in a `with`-statement, because:
1. Since then, the cleanup is done in a manner equivalent to `try`-`finally`.
2. It turned out, as noted in that PR, that cleanup had not always been done automatically. (This was contrary to the prediction given in the comment.)
3. At some point before that, the limitation that had prevented the use of `try`-`finally` no longer affected any supported version of Python.
Specifically, it appears the only limitation that this could be was the limitation lifted in Python …
> Remove obsolete note in _iter_packed_refs

- pyproject.toml
- test-requirements.txt
- test/test_util.py
Fixes #1728
This makes `xfail` markings precise in the test suite, so that only tests that are expected to fail (and do fail on CI) are marked `xfail`. This addresses both the general problem that spurious XPASS statuses make the information from `xfail`-marked tests less informative, and the specific problem focused on in #1728.
In addition, this also refactors some other recently added tests in `test_util.py`, to achieve the goals described there. I *may* soon propose other changes that build on this in other ways, but that is not included here. Basically, this just:
- Reorganizes the tests in `test_util.py`, making some of them pure `pytest` tests.
- Uses `@pytest.mark.parametrize` with the `marks=` argument to apply `@pytest.mark.xfail` to exactly the cases that currently need it, and …
> Reorganize test_util and make xfail marks precise

- .github/workflows/cygwin-test.yml
- .github/workflows/pythonpackage.yml
- git/cmd.py
- git/compat.py
- git/config.py
- git/index/fun.py
- git/index/util.py
- git/objects/submodule/base.py
- git/repo/base.py
- git/util.py
- test/lib/helper.py
- test/test_base.py
- test/test_git.py
- test/test_index.py
- test/test_installation.py
- test/test_submodule.py
- test/test_util.py
Fixes #1731
Major changes:
- Remove all uses of `is_win` and `is_posix` in `git/` and `test/`, replacing them with `os.name == "nt"` and `os.name == "posix"`, respectively.
- Fix `is_darwin` by changing it to use `sys.platform` instead of `os.name` which is never `"darwin"`.
- Add a comment in the `git.compat` module above the definitions of `is_win`, `is_posix`, and `is_darwin` stating that they are deprecated and recommending that `os.name` (or, where applicable, `sys.platform`) be used directly instead for clarity (and sometimes accuracy).
There were no uses of `is_darwin` to be replaced. Although it had been used at one time, the last reference to it appears to have been removed in 4545762 (#1295).
This doesn't emit a `DeprecationWarning` when those attributes are accessed from the …
> Deprecate compat.is_<platform>, rewriting all uses

- git/config.py
- git/exc.py
- git/index/base.py
- git/index/fun.py
- git/index/typ.py
- git/index/util.py
- git/objects/fun.py
- git/objects/tag.py
- git/objects/util.py
- git/refs/head.py
- git/refs/remote.py
- git/repo/fun.py
- test/test_blob_filter.py
- test/test_exc.py
- test/test_repo.py
Fixes #1733
In 9ccd777, several module docstrings were converted into comments or outright deleted, apparently due to at least one of them (in `git/index/fun.py`) and possibly others having broken Sphinx autodoc.
As discussed later in #1733, this no longer seems to be a problem, not even in `git/index/fun.py` where the comment included a note indicating it had.
So this converts them back to docstrings, re-adding those that were removed in 9ccd777. This also revises them, partly to avoid making outdated claims, but mostly for style and clarity. It also revises some already-present module docstrings. Other than modules 9ccd777 affected, this does not add new docstrings to modules without them.
One of the revisions made to some module docstrings here, to improve readability, is to remove …
> Revise and restore some module docstrings

- pyproject.toml
This changes the default in `pyproject.toml` so that `pytest` lists a line for each non-passing test at the end of a run, showing the test name and, where available, condensed information about the status, such as the "reason" argument for an xfailing or skipped test.
Previously only failed and errored tests were listed in the summary. With this configuration change, skipped, xfailed, and xpassed tests are listed too. The benefit is in keeping track of the status of tests. Although showing the full failure output with stack trace and relevant code under test would be too distracting for tests marked xfail, it is valuable to not merely run those tests but be able to see a line showing their names and statuses. Likewise, a number of tests are currently marked skipped, and while some of them …
> List all non-passing tests in test summaries

- test/test_util.py
These are a couple of small comment/docstring tweaks in `test_util.py` that didn't quite make it into #1739:
- Some of the tests mock `chmod` functions to better simulate the inability to change permissions on a file, but they don't mock the `lchmod` variants, at least one of which (the `pathlib.Path` method) can exists even when calling it is guaranteed to fail. This comments to explain why they are not mocked (it is so we observe such failures).
- There are a few collections of parameter sets used in the `cygpath` tests, some of which existed before any recent changes, and another of which was introduced in [#1729](https://github.com/gitpython-developers/GitPython/pull/1729) to help with precise xfail markings. This adds ["docstrings"](https://github.com/gitpython-developers/GitPython/di …
> Document some minor subtleties in test_util.py

- setup.py
Fixes #1747
This passes `encoding="utf-8"` to the `open` calls in `setup.py`, so the readme, version, and requirements files are always read as UTF-8, even on systems whose locale is not UTF-8. This fixes the bug described in #1747 where installation other than from a pre-built wheel would fail on many Windows systems using non-European languages.
The specific problem occurred with the `README.md` file. The requirements files are less likely to contain characters not in the ASCII subset, though maybe they could come to contain them, perhaps in comments. The `VERSION` file is even less likely to ever contain such characters. Nonetheless, for consistency, because it is a best practice, and because it appears to be the intent of the existing code, `encoding="utf=8"` is added for opening all …
> Always read metadata files as UTF-8 in setup.py

- .github/workflows/cygwin-test.yml
- .github/workflows/pythonpackage.yml
- pyproject.toml
- test-requirements.txt
- test/test_config.py
- test/test_diff.py
- test/test_docs.py
- test/test_fun.py
- test/test_index.py
- test/test_refs.py
- test/test_remote.py
- test/test_repo.py
- test/test_submodule.py
This expands the CI test matrix in the main test workflow, `pythonpackage.yml`, so that it is parameterized not only by Python version but also by operating system. Now it tests on both Ubuntu and Windows. It also adds conditional `xfail` markings with precise conditions and brief descriptions of the expected failures.
Most of the detailed information about specific changes in this pull request is in the commit messages. I give general information here, as well as covering, in some detail, a few areas where I think it is not readily apparent (and maybe I am wrong) what the best approach is, or what changes should be included.
A number of tests were known always to fail on Windows, with some others known to fail on Windows on particular versions or other conditions. As discussed in …
> Test native Windows on CI

- .github/workflows/pythonpackage.yml
- test/test_util.py
This expands the CI test matrix in `pythonpackage.yml` so it tests on macOS in as well as Ubuntu and Windows. To make this work, macOS has to be allowed more `extra_time` in `test_blocking_lock_file`. Previously all non-Windows systems were given the same amount of small extra time, while Windows--both native Windows and Cygwin--were given more. Now macOS is given more--even more than Windows, as it occasionally needs that.
Although macOS (at least on this CI) is slower than Windows (both native Windows and Cygwin) *in that specific part of that test* (which is timed for an assertion), it is faster than native Windows overall (and thus of course much faster than Cygwin). It looks like this would still hold up even if we did not install WSL on native Windows, albeit by a slightly smaller …
> Test macOS on CI

- git/cmd.py
- git/index/fun.py
Since Python 3.7, `subprocess.Popen` supports `close_fds=True` on all platforms, including Windows, and it is the default, including when arguments for standard streams have non-`None` values passed. 3.7 is the lowest version of Python that GitPython supports. So this omits the `close_fds=True` argument from the calls where it was present. Not passing `close_fds` at all has the same effect (in 3.7 and higher) as passing `close_fds=True`.
When the the `close_fd` argument was added to the `Popen` call in `git.cmd.Git.execute` in 1ee2afb, Python 2 was still supported. In Python 2, `close_fds` defaulted to `False`. This appears to be the reason it had been passed explicitly. It was conditioned on being on a Unix-like system because having it `True` on Windows would prevent `stdin`, `stdout`, …
> Let close_fds be True on all platforms

- AUTHORS
- git/index/base.py
- test/test_docs.py
- test/test_fun.py
- test/test_index.py
- test/test_refs.py
Fixes #1630
`IndexFile.from_tree` uses [`NamedTemporaryFile`](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) to create a temporary file in the repository's `.git` directory to pass to `git read-tree` as the operand of `--index-output`. But on Windows, the command always fails: the `git` subprocess reports it cannot write to that path. `IndexFile.from_tree` and everything that uses it are thus broken on Windows. This is the cause of #1630, as `IndexFile.reset` uses `IndexFile.from_tree`.
`git read-tree` does not actually write to the *file* itself. Instead, it attempts to rename its own separate temporary file to have its name. `git read-tree` does not require that any file exist there already. The reason we create it is to get a filename that was definitely …
> Fix IndexFile.from_tree on Windows

- git/cmd.py
When `Git.AutoInterrupt` was first implemented in ead94f2, it used `os.kill` (sending `SIGINT` to the process to terminate it). This was in 2009, and not all supported versions of Python provided `os.kill` on Windows, since it was added for Windows in [2.7](https://docs.python.org/2.7/library/os.html#os.kill) and [3.2](https://docs.python.org/3/library/os.html#os.kill) (2.6 and 3.1 [reached EoL](https://devguide.python.org/versions/#unsupported-versions) in 2013 and 2012, respectively). Catching `AttributeError` and running `TASKKILL` provided a fallback for Python versions in which `os.kill` was absent on Windows.
Since then, all supported versions have `os.kill` on Windows, and also the code of GitPython, in the `try`-block, has changed, and no longer uses `os.kill`. It now contains …
> Remove unused TASKKILL fallback in AutoInterrupt

- git/cmd.py
- git/config.py
- git/index/base.py
- git/index/fun.py
- git/objects/tree.py
- git/objects/util.py
- git/util.py
This changes `return None` to `return` where it appears in functions that are "conceptually void," i.e. cases where a function always returns `None`, its purpose is never to provide a return value to the caller, and it would be a bug (or at least confusing style) to use the return value or have the call as a subexpression.
This is already the prevailing style, so this is a consistency improvement, as well as improving clarity by avoiding giving the impression that "None" is significant in those cases.
Of course, functions that sometimes return values other than `None` do not have `return None` replaced with a bare `return` statement. Those are left alone (when they return `None`, it means something).
For the most part this is straightforward, but:
- The `handle_stderr` local function in …
> Don't return with operand when conceptually void

- .gitignore
It's sort of subjective whether, once `.gitignore` files become long, they should be grouped. The intention seemed roughly to group it, and I think this may be preferred to sorting it or doing neither.
This divides the entries into groups and labels each group with a comment.
I've also included some minor changes, which can be omitted if desired (I can amend and force push or commit again):
- Remove `/*.egg-info` because `/*egg-info` covers it.
- Add `__pycache__/` even though it should *probably* only contain `*.pyc` and `*.pyo`.
- Add `monkeytype.sqlite3.*` for compressed copies of that database. In [#1725](https://github.com/gitpython-developers/GitPython/pull/1725) I was tempted to remove `test/tstrunner.py`, but I'm glad I didn't, because it looks like MonkeyType may still be useful …
> Group .gitignore entries by purpose

- git/cmd.py
This is a fix for the ticket -> https://github.com/gitpython-developers/GitPython/issues/1616
This was already validated and catch the dubious ownership from the repo object generation to avoid confusing errors forward.
Validations results:
Catching dubious ownership
```
[root@ilabinfra-dev BlueGen]# python3
Python 3.9.16 (main, Sep 12 2023, 00:00:00) 
[GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import git
>>> repo = git .Repo('/tmp/BlueGen')
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 303, in __init__
raise InvalidGitRepositoryError(err_msg) from None
git.exc.InvalidGitRepositoryError: Detected dubious ownership …
```
> Adding dubious ownership handling

- git/__init__.py
- git/cmd.py
- git/compat.py
- git/index/__init__.py
- git/objects/__init__.py
- git/objects/submodule/base.py
- git/objects/util.py
- git/refs/__init__.py
- git/refs/log.py
- git/refs/reference.py
- git/refs/symbolic.py
- git/repo/__init__.py
- git/types.py
- git/util.py
- test/lib/__init__.py
- test/lib/helper.py
- test/test_commit.py
- test/test_config.py
- test/test_docs.py
- test/test_exc.py
- test/test_refs.py
- test/test_repo.py
- test/test_submodule.py
This includes a few small style improvements I had missed in previous PRs, but consist mostly of improvements to how and where `noqa` directives are used, and code changes (intended to be non-breaking and uncontroversial) to go along with that.
The directives are made more precise. They always give specific errors/warnings to suppress, both where that had been intended but idiosyncrasies of the syntax caused them to be broader, and where nothing had been given before. All `noqa` directives are now statement-level rather than file-level. Some of those that were no longer needed are removed with no other associated change. Some others are removed together with minimal changes to the code they complained about or to other `noqa` directives that had been ineffective (such as due to their …
> Overhaul noqa directives

- git/cmd.py
This makes the two preliminary changes discussed as possibly useful in https://github.com/gitpython-developers/GitPython/issues/1756#issuecomment-1848350451:
- **The `Git.execute` docstring is modified to include additional portability information for `kill_after_timeout`.** I've tried to do this in a way that avoids going into too much detail, but still gives enough information to allow developers of software using GitPython to infer what systems may be reasonable to use it on, or what the effects of using it on systems where it is less effective might be. I considered linking in the docstring to #1756 or discussing the race condition issue, but omitted both at this time. I'd be pleased to add such information if it is wanted.
- **The implementation of the local `kill_process` function, …
> Clarify some Git.execute kill_after_timeout limitations

- test-requirements.txt
This makes the `black` test dependency apply only to systems *other* than Cygwin. It does not block `black` from being separately installed. It does not reconfigure or otherwise affect pre-commit hooks. This is to work around a problem where the newest stable version of `black` fails to install on Cygwin. Pinning `black` to the previous stable version specifically on Cygwin would also work, but this is simpler and it is not obvious that there is much of a benefit to installing `black` (automatically) on Cygwin.
As of black 23.12.0 and [as seen](https://github.com/gitpython-developers/GitPython/actions/runs/7181278013/job/19555344996) in #1765 ([d70ba69](https://github.com/gitpython-developers/GitPython/pull/1765/commits/d70ba6941cf0f005f3f247c70233f51a0cc35969)), installing `black` builds …
> Don't install black on Cygwin

- git/objects/submodule/base.py
- test/performance/test_commit.py
- test/performance/test_streams.py
- test/test_base.py
- test/test_docs.py
- test/test_git.py
- test/test_quick_doc.py
- test/test_remote.py
- test/test_repo.py
- test/test_submodule.py
The `gc` module [was already imported](https://github.com/gitpython-developers/GitPython/blob/68272aa0028c35bd4bf36ebfd0fb55ac292b163d/git/repo/base.py#L8) at module scope in `git/repo/base.py`. Although it was moved recently, it is not a new addition. It has been present for about seven years, since f1a82e4 (#555). Importing the top-level git module or any submodule of it runs that import statement:
```python
>>> import sys
>>> "gc" in sys.modules
False
>>> import git
>>> "gc" in sys.modules
True
```
Because the `gc` module is already imported, reimporting it is fast.
Imports that there is no specific reason to do locally should be at module scope. Having them local decreased readability, in part because of how black inserts a black line between them and `gc.collect()` calls they are …
> Extract all "import gc" to module level

- test/test_diff.py
In #1765, I missed one, somehow! This fixes that.
> Extract remaining local "import gc" to module level

- test/test_submodule.py
In various places in the code, a conditional `gc.collect()` is used to allow a test to finish its work (and pass). This adds one more such place. It accordingly removes an xfail marking. `TestSubmodule.test_rename` now passes on all combinations of platform and Python version.
Like the xfail condition, running `gc.collect()` here is conditional, being done only in the specific situation the `PermissionError` occurs. Besides that it does not always run even on Windows (only in 3.12 and later), this resembles various other conditional and non-conditional gc.collect calls.
The situation is a bit odd, but I think that's--albeit by a fairly slight margin--more of a reason to convert the xfail into a `gc.collect()` than to refrain from doing so.
#1745 (under "Which versions should we test?"), …
> Replace xfail with gc.collect in TestSubmodule.test_rename

- git/index/util.py
- test/lib/helper.py
- test/performance/lib.py
- test/test_base.py
- test/test_reflog.py
- test/test_repo.py
- test/test_util.py
`tempfile.mktemp` is deprecated for security reasons and the race condition inherent to its use can have an impact on robustness even in situations where the security impact is small or nonexistent. I do not believe the changes made here are fixing security vulnerabilities; I was not able, at least so far, to think of likely ways they could be exploited. Nonetheless I believe these changes are justified, as detailed in the commit messages.
Only one of the uses of `mktemp` was in the `git` module itself. Others are in the test suite. There are a few more in the test suite where I am unsure what the best approach is to replacing them, though I hope to propose a change to eliminate them in the future. All of these considerations, as well as the general issues surrounding `mktemp` and its …
> Replace some uses of the deprecated mktemp function

- test/test_util.py
These are a couple changes to simplify and clarify the tests in `test_util.py`.
- Use `Path.touch` instead of `Path.write_bytes(b"")` in the tests. I guess I had formerly had the idea that `pathlib` gained `Path.touch` recently, but that is not at all the case. (This applies to all operating systems, but it is the more minor of the two changes.)
- Run some tests of Windows-specific environment variables on Windows only, and simplify the tests accordingly. The reason I think this makes sense now, even though it wouldn't have been the best idea when those tests were first introduced, is detailed in the [6a8ed70](https://github.com/gitpython-developers/GitPython/pull/1774/commits/6a8ed70a6003c13800d908ab055038eb61ba4ce9) message.
The latter is one of the changes listed in the "What is *not* …
> Run some Windows environment variable tests only on Windows

- git/index/util.py
- test/test_blob_filter.py
- test/test_index.py
As noted in https://github.com/gitpython-developers/GitPython/pull/1770#discussion_r1433438311, in 9e86053 (#1770) I accidentally introduced a regression in `git.index.util.TemporaryFileSwap` where the `file_path` parameter could no longer be a `Path`, even though it was (and remained) annotated in a way compatible with that.
Passing a `Path` object instead of `str` failed with `TypeError`, with a message like this (with `WindowsPath` instead of `PosixPath` on Windows, but otherwise the same):
```text
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```
Although much code that results in `TemporaryFileSwap` being used is under test, which would reveal some kinds of regressions, `TemporaryFileSwap` itself did not have any tests. It is public, so even if a `Path` were …
> Fix TemporaryFileSwap regression where file_path could not be Path

- git/index/base.py
- test/test_index.py
The `move' and `remove' index operations accept `PathLike` items, but throw a `TypeError' if any of the items are of that type.
Example:
```python
index = repo.index
index.remove(Path("foo")) # should work and not throw TypeError
```
> Fix if items of Index is of type PathLike

- git/objects/submodule/base.py
- git/remote.py
- git/util.py
- test/test_submodule.py
Fixes #1775
Fixes #1779
This includes improvements to docstrings, and also other clarity improvements such as reordering methods, in both `git.util.IterableObj` and the deprecated `git.util.Iterable` class and its associated metaclass.
For #1775, it fills in the missing information. It also rewords the surrounding information, has the less recommended `list_items` methods' docstrings refer to the more recommended `iter_items` methods (instead of the other way around), and makes some further changes along those lines detailed in dfee31f.
I think that and the other changes in this pull request, documented in commit messages and the above-linked issues this closes, make sense to do together. For #1779, I added tests for some surrounding behavior that did not appear to be under test, as well …
> Better document IterableObj.iter_items and improve some subclasses

- test-requirements.txt
Reverts gitpython-developers/GitPython#1766
Black [23.12.1](https://github.com/psf/black/releases/tag/23.12.1) has been [released](https://pypi.org/project/black/23.12.1/). This has the fix for https://github.com/psf/black/issues/4107.
We could impose a constraint that the previous version with the bug not be selected. But that version is fine on most platforms. The constraint could be made for just Cygwin, but that would make the requirement more complicated rather than less. In addition, it's probably possible, with a compiler and Python headers, to build that version for Cygwin, and if someone has done so, we shouldn't force them onto a newer version. Given that other test dependencies aren't pinned, I suggest not pinning `black` either at this time, but instead simply reverting #1766 …
> Revert "Don't install black on Cygwin"

- .github/workflows/cygwin-test.yml
- .github/workflows/pythonpackage.yml
This makes a `pip` -> `pip3` symlink in `/usr/bin` in a new step prior to the first step that runs the `pip` command. Using `pip3`, `pip3.9`, or a command like `python -m pip` would work, but this allows the Cygwin workflow to continue using the same installation commands as the main testing workflow.
Adding this fixes two problems:
1. When the pip version installed by the `python39-pip` Cygwin package is current, so that upgrading `pip` doesn't install any new command, no `pip` command is created in `/usr/local`. This has happened not to be the case for a long time, which is why the Cygwin workflow was able to pass. (That the recent failures started at the merge of [#1783](https://github.com/gitpython-developers/GitPython/pull/1783) turns out to be a coincidence: rerunning jobs on prior …
> Add missing pip in $PATH on Cygwin CI

- git/util.py
This shortens the `git.util.Iterable` docstrings, removing most of the text duplicated from `git.util.IterableObj` docstrings and instead referring the reader to the specific corresponding methods in `IterableObj`. A comment about return types that appeared in both places but really only documented `IterableObj` is likewise removed from `Iterable`.
This also reorders the classes, placing `IterableObj` before `Iterable` and its associated metaclass. This makes it easier to find, and may help remind users that `IterableObj` is the class they should use.
These changes build on those in dfee31f (#1780).
Like the current tip of the main branch, I expect this to fail the Cygwin workflow until #1784 is merged or the bug it documents is otherwise fixed. It may make sense to rebase this onto main …
> Shorten Iterable docstrings and put IterableObj first

- git/util.py
Three wrong references in docstrings to `list_items` methods had accidentally remained: one that was meant to be removed altogether, and two that were meant to be references to `iter_items`.
This completes those changes, so the docstrings make sense and references to further information are to places that have that information.
---
I don't know how I missed this, which consisted of incomplete changes both in dfee31f (#1780) and in 2b768c7 (#1785). I distinctly remember anticipating this sort of problem specifically, and deliberately checking for it, *twice*, before opening #1780, and then checking for it *twice again* before #1785.
However, examination of the diffs for those PRs reveals that the unintended/inaccurate references are present, and not a result of anything odd happening in …
> Fix incompletely revised Iterable/IterableObj docstrings

- git/cmd.py
- git/config.py
- git/diff.py
- git/index/base.py
- git/index/fun.py
- git/objects/submodule/base.py
- git/repo/base.py
- git/util.py
Fixes #1781
This does two things:
- Converts some comments on constants and other attributes to docstrings of the kind discussed in [#1734](https://github.com/gitpython-developers/GitPython/discussions/1734), throughout the codebase (not limited to the `git.cmd` module).
- Rewrites the comment, now in the form of a docstring, for `Git.USE_SHELL`, to discourage setting it to `True`, briefly explain why that can be unsafe, and explain the Windows console suppression use case for which it had previously been recommended and that it is no longer necessary or useful for that case ([#1781](https://github.com/gitpython-developers/GitPython/issues/1781)).
I have held off on calling it "deprecated," which I think is a decision that could be made later. There may be ways to limit the downsides of …
> Pre-deprecate setting Git.USE_SHELL

- git/cmd.py
- git/compat.py
- git/diff.py
- git/objects/commit.py
- git/objects/util.py
- git/util.py
This builds on the changes in #1782, actually deprecating `Git.USE_SHELL` as discussed in comments there, though no `DeprecationWarning` is currently issued on access to it. The `USE_SHELL` docstring is updated to state the deprecation while retaining most of the wording from 106bbe6. The docstring for `Git.execute`, on the `shell` parameter, is also updated to discourage passing `shell=True`, but does not declare that deprecated.
This also revises some existing deprecation notices and updates their predicted removal/breakage version number, converts more comments in docstrings (especially, but not only, those related to existing deprecations), and makes other such changes, building on the changes from 94a85d1.
A few more details are given in the commit messages.
> Deprecate Git.USE_SHELL

- git/cmd.py
The `git.cmd.handle_process_output` function is non-public (`git.cmd.__all__` only lists `Git`) but used throughout GitPython and referenced in the `git.util.RemoteProgress.new_message_handler` docstring. Its `finalizer` argument is annotated to accept an optional callable that always returns `None`. It is always used this way in GitPython and `RemoteProcess.new_message_handler` is annotated accordingly. However, the `handle_process_output` docstring and implementation had documented the return value as the result of the finalizer, and the implementation had forwarded that result if passed.
This modifies the docstring and implementation to disregard any result, in accordance with the everywhere-annotated assumption that the finalizer is conceptually void and the absence of any code in …
> In handle_process_output don't forward finalizer result

- git/index/base.py
- git/index/util.py
In `git.index.base.IndexFile.from_tree`, control was never able to fall off the end, but `mypy` reported a "Missing return statement" because it could not infer that the context manager didn't suppress any exceptions.
This was for two reasons. An `ExitStack` context manager suppresses exceptions in some uses and not others, depending on the context manager objects its `enter_context` method is called with. In this case, that was sufficient to produce the `mypy` warning regardless of other changes, so I converted it to nested `with`-statements. The nesting depth is only 2, so this is not really any worse. (I also reworded the comments for clarity and adjusted their spacing.)
The more important cause, however, could also produce this warning in code that uses GitPython, as …
> Fix mypy warning "Missing return statement"

- .pre-commit-config.yaml
- git/cmd.py
- git/index/fun.py
- git/util.py
- test/fixtures/polyglot
- test/lib/helper.py
- test/test_git.py
- test/test_index.py
- test/test_installation.py
Although #1636 caused GitPython to avoid using an untrusted search path on Windows under the most typical circumstances, it turns out that some cases remained. I believe only two remain at this time. This pull request fixes those.
This vulnerability was reported privately, and a full public writeup is not available at this time--I want to get this PR out as coordinated/requested, without extra delays. However, some details are present in commit messages, and I'll try to update this in some way in the future, either to include more information or to link to a relevant advisory or other source.
*Edit:* The CI status on all commits appears to be as I expected and intended.
> Fix two remaining Windows untrusted search path cases

- test-requirements.txt
- test/test_index.py
Fixes #1797
The `WinBashStatus` class in `test_index.py`, introduced in #1745, had used the `sumtypes` library to express the various cases relevant to xfail markings and troubleshooting and, where applicable, to express some associated debugging information. This includes the `Inapplicable` case, so `sumtypes` was used on all systems, not just Windows, which also usefully allowed the other cases to be inspected dynamically on any system, and allowed xfail markings to be written without excess complexity.
However, that only used a small fragment of `sumtypes` functionality, which can be expressed with only minor inelegance with explicit data classes. This pull request makes that change and removes `sumtypes` as a test dependency.
Because the `sumtypes` dependency was apparently causing …
> Remove test dependency on sumtypes library

- doc/requirements.txt
Fixes #1802
This fixes version incompatibilities with major version 4 of Sphinx, which GitPython is still using for the time being. Some plugins that previously had depended back on Sphinx have had those dependencies removed to avoid dependency cycles, but the effect is that `pip` no longer is aware of or able to enforce version compatibility, and newer plugin versions than can actually run with Sphinx 4 are installed instead of older, usable versions.
This fixes the problem by pinning each of the affected Sphinx plugins' latest actually compatible versions, i.e., latest versions that do not need Sphinx 5 or higher. Two of the plugins are pinned to ranges of a few versions rather than individual versions in order to preserve compatibility with Python 3.7 without making …
> Pin Sphinx plugins to compatible versions

- AUTHORS
- git/objects/tree.py
- test/test_tree.py
https://github.com/gitpython-developers/GitPython/issues/369
> fix: treeNotSorted issue

- git/util.py
*This is not related to the issue of when a noop handler should actually be used, so it is independent of #1806.*
The `NullHandler` class in `git.util` was added when merging #300, to allow a noop handler to be used on Python 2.6, since the standard library `logging.NullHandler` class was added in Python 2.7.
When introduced in d1a9a23, the `git.util.NullHandler` class was also patched into the logging module, but that has no longer been done since 2fced2e (#979), nor does GitPython make other use of it.
`git/util.py` defines `__all__`, which does not list `NullHandler`. As `NullHandler` is not otherwise documented to be public, it is a bug for any code outside GitPython to use it, and removing it is not a breaking change. So there should be no need for a deprecation period or to wait …
> Remove git.util.NullHandler

- git/cmd.py
Fixes #1804
This clarifies the comment that explains the significance of setting the `Git.GIT_PYTHON_GIT_EXECUTABLE` attribute when running Git failed but the attribute wasn't set before.
This happens in the code path in `Git.refresh` where `has_git` is `False` and `old_git` is `None`, provided the refresh mode doesn't call for the initial refresh to raise an exception on failure.
It was previously described in terms of a "first" and "second" import, but as discussed in #1804, the rationale and effect were not altogether clear. This uses wording along the lines of what I suggested there, adjusted a bit for context.
> Clarify why GIT_PYTHON_GIT_EXECUTABLE may be set on failure

- git/cmd.py
- git/remote.py
- test/test_git.py
Fixes #1809
Fixes #1811
This modifies `Git.refresh` to report the attempted Git command rather than always `git` even if a different command was used. This affects the `command` attribute of the `GitCommandNotFound` exception, as well as (and automatically) the text displayed as `cmdline:` since that is from that attribute.
It also expands and adds more tests of `git.refesh` (which calls `Git.refresh`) to encompass this behavior, verifying that they fail before #1809 is fixed and pass afterwards, as well as verify some behavior that was already established but not yet under test.
Since #1811 would otherwise be exacerbated by these changes, I've also made it so those tests roll back the global changes they make that may affect other test by calling `git.refresh()` with no arguments. I …
> Report actual attempted Git command when Git.refresh fails

- git/cmd.py
- git/config.py
- git/objects/commit.py
- git/objects/submodule/base.py
- git/objects/submodule/root.py
- git/remote.py
- git/repo/base.py
- git/util.py
- test/lib/helper.py
- test/test_git.py
- test/test_index.py
Fixes #1806
This stops adding `NullHandler` instances to GitPython's loggers. As noted in #1806, when they were added in #300 this prevented errors when GitPython logged messages and logging was not enabled, but since Python 3.2 there is a logger of last resort providing a nicer default behavior of showing the messages. (They are still shown with better formatting if logging is configured, even if just done with `logging.basicConfig()`, so applications should still typically configure logging.)
This also makes a few more minor related changes, detailed in the commit messages. This includes changing variable names from `log` to `_logger`, as mentioned in https://github.com/gitpython-developers/GitPython/issues/1806#issuecomment-1907690901, as well as consistently passing `__name__` to …
> Don't suppress messages when logging is not configured

- .github/workflows/cygwin-test.yml
The latest currently packaged version of Python 3.9 for Cygwin is 3.9.18 (provided by the Cygwin package python39 at version 3.9.18-1). That version, at least as we are using it, has a problem where `pip` stalls indefinitely on some PyPI package downloads. This is the problem encountered around the time #1813 was reviewed and merged, and discussed in comments there, but it was not triggered by that or any other change in GitPython.
In https://github.com/gitpython-developers/GitPython/pull/1813#issuecomment-1912783151 I said I couldn't produce it locally, but since then I have been able to do so. I believe the reason I couldn't produce it locally at that time was that I had not cleared cached `pip` downloads in `~/.cache`. I am unsure of the exact condition under which the problem occurs, …
> Pin Python 3.9.16 on Cygwin CI

- git/cmd.py
- test/test_git.py
Fixes #1808 
Code changes in the `git` module:
- When the initial call to `git.refresh` that happens on import fails to find a `git` command and is configured to warn, it warns using a logger rather than with `print`. Although this is conceptually a warning, it is emitted with level `CRTICAL`, for the reasons given in ac50d8e (the commit in this PR that changes the tests for it).
- The message is changed to document this.
- A few more values, for existing `GIT_PYTHON_REFRESH` modes, are added as synonyms. No new modes are added, nor are their states expanded. The motivation for adding new synonyms is so `log` achieves logging, i.e., it is another way to say `warn`. But `l` is also added as its short form. (This might ordinarily be objected to on the grounds that, when written as `l` and …
> Have initial refresh use a logger to warn

- git/cmd.py
- test/test_git.py
- test/test_index.py
This builds on the changes in #1815 by omitting the `WARNING: ` prefix from the message itself that is produced when `GIT_PYTHON_REFRESH` is set to `warn` or a synonym (such as `w` or `log`) and the initial refresh performed at import time fails. This is the change suggested in https://github.com/gitpython-developers/GitPython/pull/1815#issuecomment-1925244493.
When logging is not configured, this changes what we see when the initial refresh fails:
```diff
-WARNING: Bad git executable.
+Bad git executable.
```
This may be considered slightly worse than before, but the advantage is that it doesn't print something that looks like a severity (or a redundancy) when logging *is* configured. For example, with common logging configuration such as by `logging.basicConfig()`, we get this …
> Omit warning prefix in "Bad git executable" message

- .github/workflows/pythonpackage.yml
This adds CI test jobs that run on ARM processors. Specifically, it adds `macos-14` as a value for `os` in the CI test matrix. The new macOS 14 runners use Apple Silicon M1 systems (64-bit ARM CPUs), allowing GitPython to be tested on AArch64/ARM64 [actions/python-versions](https://github.com/actions/python-versions) builds of Python, such as `python-3.12.1-darwin-arm64.tar.gz`.
- [GitHub Actions: Introducing the new M1 macOS runner available to open source!](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)
- [GitHub Actions: macOS 14 (Sonoma) is now available](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/)
Not all versions of Python that GitPython supports are currently …
> Test with M1 macOS CI runner

- test/lib/helper.py
- test/test_tree.py
Fixes #1824
This fixes temporary directory creation and cleanup in `test_tree_modifier_ordering`, extracts its helper to a separate method, slightly extends `@with_rw_directory` so it can be used directly on helper methods while still logging accurate descriptions, and uses it to ensure cleanup of the temporary directory that is used by the helper to generate the expected value that the test will compare its results to.
Because that decorator was not previously used on any test helper methods, only on test methods, it is not obvious that my use of it on the helper, and my modification to it to properly support such use, is justified. The reason I think it is justified is that we really do want to complete cleanup, including deleting the temporary directory, before beginning to use the …
> Keep temp files out of project dir and improve cleanup

- .github/workflows/alpine-test.yml
- test/test_util.py
As suggested in https://github.com/gitpython-developers/GitPython/pull/1745#issuecomment-1838018193, this adds a test job that runs the tests inside a Docker container.
This can be done with Ubuntu in the container, but instead I used Alpine Linux in the container. This provides a greater variety of platforms GitPython tests on, potentially uncovering some bugs that would otherwise go undetected. In particular, Alpine Linux does not satisfy some of the assumptions that are sometimes made about platforms, as it does not, by default, have `bash`; its `ps` and related tools are not procps; it does not have GNU coreutils or GNU libc; and so forth.
No tests had to be marked `xfail` for this. In particular, as noted in https://github.com/gitpython-developers/GitPython/pull/1745#issuecomment-1837 …
> Test in Docker with Alpine Linux on CI

- git/cmd.py
- test/test_git.py
- test/test_index.py
Fixes #1829 - cache invalidation
Fixes #1830 - typing
Fixes #1833 - parsing
Fixes #1836 - serialization
Much of the design in the fixes for #1830, #1833, and #1836, as well as why I think it makes sense to include them here with #1829, is already largely covered in the discussion/comments in those three issues.
For #1829, which I would regard to be the biggest of the changes here, and which is the change for which the most additional code is added to the test suite, I made sure to preserve three important properties of the code:
1. Refreshing is global but affects all `Git` instances. Changing the way refreshing itself fundamentally works is beyond the scope of this PR and would also be a breaking change that I think could only be made in a new major release, and there are good reasons …
> Fix version_info cache invalidation, typing, parsing, and serialization

- .readthedocs.yaml
- doc/source/conf.py
Fixes #1840
This configures Read the Docs builds to be more like local builds in two ways:
- Pass `-W`, as is done in a local build with `make -C doc html`, so that if there are broken references, the build fails.
- Install dependencies. This [configures the Python environment](https://docs.readthedocs.io/en/stable/config-file/v2.html#python), via the `python.install` key, so that RTD builds install requirements.
More specifically on dependency installation, it does two things:
1. The equivalent of `pip install .`, which installs the project and its dependencies (though not any extras). This includes the gitdb dependency, which is needed to import GitPython's `git` module to populate sections in the API Reference page ([#1840](https://github.com/gitpython-developers/GitPython/issues/1840)) …
> Build online docs (RTD) with -W and dependencies

- git/cmd.py
This makes the refresh failure message fill in the made-up path `"/full/path/to/git"` as an argument to `git.refresh`. This small expansion serves two purposes:
- To clarify what kind of explicit refresh is being described: passing a path to `git.refresh`.
- To clarify what kind of path should typically be used when this is done: a full path.
The latter clarification is more important because it cannot be reasoned out from the message and the interface of `git.refresh` and related functions, though it can be learned from their docstrings since #1829, from their implementations, or by trial and error.
I'm not sure how much I like the change in the error message. It seems better than before, but there are three weaknesses:
- The path passed to `git.refresh` doesn't actually have to be a …
> Suggest full-path refresh() in failure message

- git/repo/base.py
Fixes #1835.
As this pull request only affects the typings and does not change the behavior in any way, I did not write a test for the changes I made. 
While a test definitely *could* be written to see if the library does parse a blame output with uncommited changes, I don't perticularily think this is necessary, as the output format of the `git blame -p` command is the same as if there had been a commit, just with hard-coded values (such as the null SHA as the commit hash). Therefore, there is no reason the parsing would fail.
I did manually test both methods with the `None` rev parameter and they do give the expected behavior. 
Let me know if you want me to change anything else!
> `repo.blame` and `repo.blame_incremental` now accept `None` as the `rev` parameter.

- git/diff.py
- test/test_diff.py
Closes #1828
This change forces `diff` to always use the default diff driver when `create_patch=True`. So any user using external diff can reproduce the same result as users that don't.
> Make sure diff always uses the default diff driver when `create_patch=True`

- doc/source/reference.rst
- git/cmd.py
- git/compat.py
- git/db.py
- git/remote.py
Fixes #1854
This adds some missing modules in the API Reference. It adds the modules covered under "case 1" (top-level `git`, but only `refresh` and, as before, `__version__`) and "case 3" (the three leaf modules whose documentation wasn't previously emitted), as I classified them in #1854. It does not add "case 2".
Even if this is what should be done, there is some question about the specifics:
- I don't know what top-level entries should be grouped under in the existing naming convention. Its relationship to the actual module names is usually predictable but not precise. The general pattern doesn't allow me to predict a useful name for the section at the top that now contains `git.__version__` and `git.refresh`; it was previously called "Version", which is no longer suitable. I picked …
> Expand what is included in the API Reference

- .readthedocs.yaml
Although documentation resumed being built in 634151a, and the RTD theme and API Reference section were restored in 64ad585 (#1843), documentation for download did not resume being built, with 3.1.37 (not 3.1.42) being the latest version listed at:
- https://readthedocs.org/projects/gitpython/downloads/
Three kinds of downloadable documentation are supported -- PDF, ePub, and HTML -- and all three were previously being built but all have stopped.
This attempts to resume building all three, listing `all` under the `formats` key in .readthedocs.yml. `all` currently should have the same effect as listing all of `htmlzip`, `pdf`, and `epub`, per:
- https://docs.readthedocs.io/en/stable/downloadable-documentation.html
- https://docs.readthedocs.io/en/stable/config-file/v2.html#formats
---
As I …
> Restore building of documentation downloads

- git/remote.py
- git/util.py
- test/test_remote.py
Replacing the \s whitespace characters with normal spaces (" ") to prevent breaking on unicode whitespace characters (e.g., NBSP). Without this, if a branch name contains a unicode whitespace character that falls under \s, then the branch name will be truncated.
> Updating regex pattern to handle unicode whitespaces.

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- Makefile
- README.md
- git/cmd.py
- git/compat.py
- git/index/fun.py
- git/objects/fun.py
- git/objects/tree.py
- git/objects/util.py
- git/remote.py
- git/util.py
- pyproject.toml
- test-requirements.txt
- tox.ini
following #1862 we could also use just Ruff for better consistency between lint and formatter
> lint: switch Black with `ruff-format`

- README.md
- tox.ini
There are some changes that I should have proposed and/or made in `README.md` and `tox.ini` related to #1862, which are made slightly more needed by #1865. This brings the readme and tox configuration up to date for both #1862, which was merged, and #1865, which I think will be merged soon ~~pending one small change~~. Further related changes should be eventually be made in both, but they will depend on future decisions, and nothing bad will happen if changes end up not being made for an extended time after merging both #1865 and this PR.
The changes here seem significantly more cumbersome to recommend be included in #1865 than to do separately, and because they also apply to the situation brought about since #1862, I don't think they need to be done there or done before that is merged. I …
> Update readme and tox.ini for recent tooling changes

- .github/workflows/lint.yml
- tox.ini
See 4c034db for details on the main changes.
This adds tox environments for both linting and format checking with Ruff, specifying Ruff as a dependency and calling it in such a way that it does not mutate files in the working tree, since one expects tox not to do that. This still has tox use pre-commit to run other hooks (which do not modify files).
Since none of these modify files, they all can and should run automatically when `tox` is run with no arguments, so they are added to the `env_list` (which the old lint env had been removed from in #1868, pending a change like this).
With this approach taken, there is no clear use for the already-unused manual hook stage in the near future anymore, and it's easy to bring back if needed, so I've also removed that, including in the CI linting …
> Split tox lint env into three envs, all safe

- .pre-commit-config.yaml
- pyproject.toml
- requirements-dev.txt
Changes:
- Lets Ruff scan `doc/source/conf.py`, and other Python modules in `doc` outside `build` if there were any (00ff7e3).
- Adds comments on all suppressed Ruff rules and puts all of `pyproject.toml` in closer to the same style (4814775).
- Adds Ruff (and ShellCheck, which could've been added before) to the file currently used to list tools not listed as dependencies (a8a73ff).
- Bumps pre-commit hook versions, which brings small benefits for Ruff and ShellCheck (ff1ebf8).
> Slightly broaden Ruff, and update and clarify tool configuration

- .github/workflows/pythonpackage.yml
- .readthedocs.yaml
- setup.py
- tox.ini
Much as GitPython has a `test` extra to aid development by installing testing and--currently--most linting dependencies, this adds a `doc` extra that installs Sphinx and its theme and plugins. The `test` extra is built by parsing `test-requirements.txt`, and similarly the new `doc` extra is built by parsing `doc/requirements.txt`. The previous approach of running `pip install -r doc/requirements.txt` continues to work.
The following are updated to use the new extra:
- The Read the Docs configuration in `.readthedocs.yaml`.
- Documentation build testing step in `pythonpackage.yml`.
- Documentation building tox environment in `tox.ini`.
Before doing this, I factored out shared logic in the way metadata files are read in `setup.py`, wrote that code in a more streamlined way, and removed what …
> Add a "doc" extra for documentation build dependencies

- git/objects/submodule/base.py
This includes a brief description of the `Submodule.__init__` *parent_commit* parameter in its docstring, rather than only referring to the `set_parent_commit` method, whose semantics differ due to conversation and validation, and which accepts more types than just `Commit` or `None`.
The wording is based on wording in `set_parent_commit`, adjusted for the difference in types, and `set_parent_commit` remains reference for further details.
This builds on 1f03e7f (#1859) in improving the situation described in #1869.
> Describe `Submodule.__init__` parent_commit parameter

- git/types.py
The `Tree_ish` union omitted `TagObject`, whose instances are only sometimes tree-ish, and unlike `Commit_ish` before #1859, it is not inherently a bug to define `Tree_ish` this way.
However, this `Tree_ish` type actually has only one use in GitPython (which was also the case before the changes in #1859): as, itself, an alternative in the union used to annotate the rev parameter of the `Repo.tree` method (whose other alternatives are `str` and `None`). A `TagObject` may be passed, and if it points to a tree or commit then that will be resolved. Just to avoid a mypy error, code doing that would (before this change) have to convert it to `str` first.
That annotation should be improved, and the best way to do it is to keep it written the same way but change the definition of `Tree_ish` in …
> Include TagObject in git.types.Tree_ish

- git/types.py
This revises the docstrings of the `Tree_ish` and `Commit_ish` unions, to make clearer that tags objects are usually used to identify commits and are thus usually tree-ish and commit-ish.
This change relates to the discussion in #1878, starting at https://github.com/gitpython-developers/GitPython/pull/1878#pullrequestreview-1938343498.
> Clarify how tag objects are usually tree-ish and commit-ish

- git/repo/fun.py
- git/util.py
This applies two minor Cygwin-related clarifications, one of which is theoretically a bugfix though it affects conceptually non-public code that is currently not used in a way that could invoke the bug. Some specific details are in commit messages.
The second commit, 988d97b, which fixes `COM` to `.COM` in the fallback for the `PATHEXT` environment variable--whose omission is almost certainly a typo, going back to the function's introduction in e6e23ed (#533)--is theoretically a bugfix. But as noted there, this code is only called when the Python interpreter is a native Windows program, but the function it is a part of is only called when the Python interpreter is *not* a native Windows program. (Also, it would be pretty unusual for the `git` executable to have a `.com` extension.)
--- …
> Fix typo in _get_exe_extensions PATHEXT fallback

- pyproject.toml
This removes the `--disable-warnings` option from those specified in `pyproject.toml` for `pytest` to use automatically.
I originally tried this in the hope that it would show a warning for misspelled keyword arguments passed when constructing pytest marks (which should not be confused with misspelling the mark itself, which is something pytest can warn for). That bug (#1893) was discovered in #1888. *This turns out not to be useful for that at all*, so I'm opening this PR separate from anything related to that.
Nonetheless, there doesn't seem to be a significant disadvantage to showing this output, which is not easy to mistake for errors or test failures, and which might potentially help catch other kind of cases where a misspelling that intuitively feels like it would lead to an error …
> Don't suppress pytest warning summaries

- git/refs/head.py
This updates the comment in `HEAD.reset` about why `--mixed` is omitted from the git command constructed to perform a reset where paths are being passed, adding specific information about the git versions where this is deprecated, and changing the more-info link from an old GitPython issue that is no longer retrievable to #1876.
See #1876 for details.
> Update the comment about `--mixed` and paths

- git/remote.py
When we try to execute 
submodule_update(recursive=True, init=True) 
in Repo class with shallow submodules, command
git fetch --progress -v origin 
sometimes print log such as
=5 = [up to date]      zm/160_uwp              -> origin/zm/160_uwp
but it doesn't satisfy filter:
r"^ *(.) (\[[\w \.$@]+\]|[\w\.$@]+) +(.+) -> ([^ ]+)( \(.*\)?$)?"
and throw exception.
I've updated it so that it works correctly.
> Fixed an error updating shallow submodules

- fuzzing/README.md
- fuzzing/local-dev-helpers/Dockerfile
Adds a Dockerfile to enable easily executing the fuzz targets directly inside a container environment instead of directly on a host machine. This addresses concerns raised in PR #1901 related to how `fuzz_tree.py` writes to the real `/tmp` directory of the file system it is executed on as part of setting up its own test fixtures, but also makes for an easier to use development workflow.
I also added a warning to the `fuzzing/READEME` strongly suggesting users only execute the targets inside of Docker.
See this related comment on PR #1901 for additional context: https://github.com/gitpython-developers/GitPython/pull/1901#issuecomment-2063818998
> Dockerize "Direct Execution of Fuzz Targets"

- fuzzing/fuzz-targets/fuzz_config.py
- fuzzing/fuzz-targets/fuzz_tree.py
- fuzzing/oss-fuzz-scripts/build.sh
A Git executable is not globally available in the ClusterFuzz container
environment where OSS-Fuzz executes fuzz tests, causing an error in the fuzz
harnesses when GitPython attempts to initialize, crashing the tests before they
can run.
To avoid this issue, we bundle the `git` binary that is available in the OSS-Fuzz
build container with the fuzz harness via Pyinstaller's `--add-binary` flag in
`build.sh` and use GitPython's `git.refresh(<full-path-to-git-executable>)`
method inside a Pyinstaller runtime check to initialize GitPython with the
bundled Git executable when running from the bundled application.
In all other execution environments, we assume a `git` executable is available
globally.
Fixes:
- https://github.com/gitpython-developers/GitPython/issues/1905
- …
> Fix Fuzzer Crash in ClusterFuzz Due to Missing Git Executable

- fuzzing/fuzz-targets/fuzz_config.py
- git/config.py
- test/test_config.py
Fixes: https://github.com/gitpython-developers/GitPython/issues/1887
Improve the guarding `if` check in `GitConfigParser`'s `string_decode` function to safely handle empty strings and prevent `IndexError`s when accessing string elements.
This resolves an IndexError in the `GitConfigParser`'s `.read()` method when the config file contains a quoted value ending with a new line.
> Fix `IndexError` in `GitConfigParser` When a Quoted Config Value Contains a Trailing New Line

- fuzzing/fuzz-targets/fuzz_config.py
- fuzzing/fuzz-targets/fuzz_tree.py
This is a second attempt at #1906 and should resolve:
- https://github.com/gitpython-developers/GitPython/issues/1905
- https://github.com/google/oss-fuzz/issues/10600
PR #1906 had the right idea but wrong implementation. The differences between the ClusterFuzz image that it was supposed to fix and the OSS-Fuzz image where it was tested led to the issue not being fully resolved.
The root cause of the issue is the same: A Git executable is not globally available in the ClusterFuzz container environment where OSS-Fuzz executes fuzz tests.
#1906 attempted to fix the issue by bundling the Git binary and using
GitPython's `git.refresh(<full-path-to-git-executable>)` method to set it inside the `TestOneInput` function of the test harness.
However, GitPython attempts to set the binary at import …
> Attempt 2 - Fix Missing Git Executable Causing ClusterFuzz Crash

- .pre-commit-config.yaml
Since `fix` may do some additional changes, it makes sense to first run fixing and the formatting so you may need to run pre-commit only once in case fixing wont be compatible with formatting
> lint: switch order Ruff's hooks `fix` -> `format`

- fuzzing/fuzz-targets/fuzz_diff.py
Adds a new `fuzz_diff.py` fuzz target that covers `Diff` class initialization using fuzzed data.
Local test run stats:
```
#46050	DONE   cov: 308 ft: 338 corp: 8/241b lim: 499 exec/s: 51 rss: 86Mb
Done 46050 runs in 901 second(s)
stat::number_of_executed_units: 46050
stat::average_exec_per_sec:     51
stat::new_units_added:          2
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              86
```
> Add `Diff` Fuzz Target

- fuzzing/fuzz-targets/fuzz_diff.py
Fuzz Introspector was reporting a high percentage of fuzz blockers in the `fuzz_diff` test. This means the fuzzing engine was unable to gain visibility into functions lower in the call stack than the blocking functions, making it less effective at producing interesting input data.
This clears a large percentage of the fuzz blockers by adding fuzzer instrumentation to them via the `@atheris.instrument_func` decorator.
**Fuzz Introspector Before & After Screenshots**
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details>
> Instrument test utility functions to increase fuzzer efficiency

- .github/workflows/cygwin-test.yml
As shown in [this run on my fork](https://github.com/EliahKagan/GitPython/actions/runs/9246034785/job/25433125087#step:13:7106), the CI test job for Cygwin is failing now. This fixes that.
The first commit in this pull request just demonstrates that the failure is due to the upgrade of the Cygwin `git` package from 2.43.0-1 to 2.45.1-1. Although that commit makes test pass, I recommend against following that approach, mainly because the new version contains [multiple security updates](https://github.com/git/git/commit/83f1add914c6b4682de1e944ec0d1ac043d53d78) (coming in with the upstream [2.45.1](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.45.1.txt) version, not with any downstream patches), but also because the older version will eventually be dropped from …
> Add the `.git` subdir as another `safe.directory` on Cygwin CI

- fuzzing/fuzz-targets/fuzz_submodule.py
- fuzzing/fuzz-targets/utils.py
[Fuzz Introspector heuristics suggest](https://storage.googleapis.com/oss-fuzz-introspector/gitpython/inspector-report/20240527/fuzz_report.html#Analyses-and-suggestions) the Submodule API code represent "optimal analysis targets" that should yield a meaningful increase in code coverage. The changes here introduce a first pass at implementing a fuzz harness that cover the primary APIs/methods related to Submodules. Of particular interest to me is the `Submodule.config_writer()` coverage.
Please note however, there is likely plenty of room for improvement in this harness in terms of both code coverage as well as performance; the latter of which will see significant benefit from a well curated seed corpus of `.gitmodules` file like inputs. The `ParsingError` raised by the fuzzer without a …
> Add Submodules Fuzz Target

- fuzzing/fuzz-targets/fuzz_submodule.py
- fuzzing/fuzz-targets/utils.py
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69350 (See 7b684cd43cf0f9c54adb8a8def54fa07f5cfd145)
Also:
- Improves file name generation to prevent "File name too long" OSError's (6c00ce602eb19eda342e827a25d005610ce92fa8)
- Improves `fuzz_submodule.py` coverage & efficacy (2a2294f9d1e46d9bbe11cd2031d62e5441fe19c4)
> Add graceful handling of expected exceptions in fuzz_submodule.py

- git/diff.py
- git/index/base.py
Example issue with DiffIndex:
```python
repo = git.Repo(path_dir)
diff = repo.index.diff(None)
modified_files = [d for d in repo.index.diff(None)]
reveal_type(modified_files) # list[Unknown] instead of list[Diff]
```
Example issue with IndexFile:
```python
path: os.PathLike = ...
repo = git.Repo(path_dir)
repo.index.add(path)
```
> typing fixes - DiffIndex generic type and IndexFile items

- fuzzing/fuzz-targets/fuzz_submodule.py
ClusterFuzz runs of the `fuzz_submodule` target have been failing because the `git` import was placed before the condition that sets the Git executable path 😞 
The order in which `git` is imported matters because it attempts to find a Git executable as the import is loaded (via `refresh()` in `git/__init__.py`.) As per #1909, we configure the ClusterFuzz environment to use a bundled Git executable via the env variable condition in all fuzz targets.
> Fix Improper Import Order Breaking `fuzz_submodule` Fuzzer

- git/diff.py
- test/deprecation/test_basic.py
Hello 👋,
in https://github.com/gitpython-developers/GitPython/pull/1886 and https://github.com/gitpython-developers/GitPython/commit/e7dec7d0eecc362f02418820a146735a68430fbd a proper warning message was introduced for the usage of `Diff.renamed` pointing to use `Diff.renamed_file`.
However, the usage of this property wasn't changed in the `iter_change_type` (since 3 years at that), so the internals use deprecated code 😞 
https://github.com/gitpython-developers/GitPython/blob/9fbfb718bf2e66f6f842e496cf304112b438e864/git/diff.py#L328-L329
Given that the code wasn't reported yet, perhaps I'm doing something wrong using the `iter_change_type` and there are better ways 👀 I'm using a custom MkDocs hook to run GitPython and check for renames to automatically create redirects mappings for paths, …
> Fix iter_change_type diff renamed property to prevent warning

- test/test_docs.py
Small change on documentation to make it clear how to use the `repo.git` object (not to confuse `import git`).
This is not a fix for #1924, but was related due to this documentation string.
> fixed doc to not faulty do #1924

- git/diff.py
- test/test_diff.py
Some repositories contain files / directories beginning by a space in their history (example : https://github.com/react-component/field-form/commit/0e81dc0d69d198d644b44eb4f84d875777c03581).
The current version of GitPython returns this space _sometimes_ when doing a diff (depending on whether the space is in `a_path` or `b_path`).
```
Python 3.12.3 [...] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import git
>>> git.Repo.clone_from("https://github.com/react-component/field-form", "field-form") # example repository
<git.repo.base.Repo '/tmp/field-form/.git'>
>>> r = git.Repo("field-form")
>>> c = r.commit("0e81dc0d69d198d644b44eb4f84d875777c03581") # commit where there is a space
>>> d1 = c.diff(c.parents[0])[0] # first diff
>>> d1.a_path …
```
> fix: fix incoherent beginning whitespace

- .pre-commit-config.yaml
- README.md
- doc/source/changes.rst
- git/index/base.py
- git/objects/util.py
- git/remote.py
- pyproject.toml
- test/test_exc.py
- test/test_index.py
Just a suggestion to add a check for typos and maybe let's fix some without breaking API
> lint: add typos check

- AUTHORS
- git/objects/commit.py
- git/types.py
- git/util.py
- test/fixtures/diff_numstat
- test/test_commit.py
- test/test_stats.py
This allows to not only get the total, inserted or deleted number of lines being changed but also the type of change like Added (A), Copied (C), Deleted (D), Modified (M), Renamed (R), type changed (T), Unmerged (U), Unknown (X), or pairing Broken (B)
> Add type of change to files_dict of a commit

- .github/workflows/pythonpackage.yml
Some of the CI tests use WSL. This switches the WSL distribution from Debian to Alpine, which might be slightly faster. For the way it is being used here, the main expected speed improvement would be to how long the image would take to download\*, as Alpine is smaller.
(The reason for this is thus unrelated to the reason for the Alpine docker CI test job added in #1826. There, the goal was to test on a wider variety of systems and environments, and that runs the whole test suite in Alpine. This just changes the WSL distro, used by a few tests on Windows, from Debian to Alpine.)
Two things have changed that, taken together, have unblocked this:
- https://github.com/Vampire/setup-wsl/issues/50 was fixed, so the action we are using is able to install Alpine Linux. See: …
> Use Alpine Linux in WSL on CI

- .github/workflows/pythonpackage.yml
This keeps only the `macos-14` jobs, which run on Apple Silicon M1, and removes the `macos-13` jobs, which ran on x86-64. This relates to the commented discussion in #1944. There would also be the option of keeping some of them, but removing all of them decreases the workload the most while also being the simplest.
It also uses the label `macos-latest` instead, which is currently equivalent to `maos-14`.
- Some information about the situation with `macos-latest` and the benefit of using it is presented in the second commit message.
- That these jobs really are running on macOS 14, and more importantly that they are really running on ARM64, can be verified by examining the output of "Set up job" step. [Here's an example.](https://github.com/EliahKagan/GitPython/actions/runs/10073515669/job/ …
> Remove the non-ARM macOS CI jobs

- fuzzing/fuzz-targets/fuzz_submodule.py
- fuzzing/fuzz-targets/utils.py
- fuzzing/oss-fuzz-scripts/build.sh
- fuzzing/oss-fuzz-scripts/container-environment-bootstrap.sh
- pyproject.toml
Fixes the buggy `fuzz_submodule` harness which is the root cause of all recent OSS-Fuzz/Monorail issues opened.
There are several distinct changes introduced here, but they are all addressing the same related exception handling weaknesses in the fuzz harness code so I think they make sense in a single PR.
Commit messages should provide relevant context, however I want to explicitly mention one change that is particularly noteworthy: the introduction of a mechanism to filter shallow errors using an explicit exceptions list.
This new pattern involves generating an 'explicit-exceptions-list.txt' by scanning for 'raise' and 'assert' statements via `git grep` during the container build step. The list helps the fuzz harness to distinguish between expected and unexpected exceptions, …
> Fix Several Bugs in the `fuzz_submodule` Causing a lot of False Alarms in the OSS-Fuzz Bug Tracker

- fuzzing/fuzz-targets/fuzz_submodule.py
Fuzzing inputs sometimes produce directory paths that are protected inside the fuzzer execution environment. This is not an issue in GitPython's code, so it should not crash the fuzzer.
Fixes OSS-Fuzz Issue 69456:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69870
> Gracefully handle `PermissionError` exceptions that crash fuzzer

- fuzzing/fuzz-targets/fuzz_submodule.py
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71095
Fuzzing data can generate filenames that trigger:
> OSError: [Errno 36] File name too long
The changes here add handling for these exceptions because they di not indicate a bug and should not crash the fuzzer.
> Fuzzing: Gracefully Handle Uninteresting Error to Fix OSS-Fuzz Issue

- doc/requirements.txt
- git/index/base.py
- git/objects/tag.py
This upgrades Sphinx from 4.3.2 to 7.1.2.
The old pinned version and its explicitly constrained dependencies are retained for now for Python 3.7 so that documentation can be built even with 3.7. (This could maybe be removed soon as a preliminary step toward eventually dropping 3.7 support.)
For Python 3.8 and higher, version 7.1.2 is used, allowing later patch versions but constrained to remain 7.1.\*. This is so the same versions are likely to be selected on all Python version from 3.8 and higher, to minimize small differences in generated documentation that different versions could give, and also to simplify debugging.
**The reason to upgrade Sphinx now is to support Python 3.13**, which shall be (and, in the pre-releases available, is) incompatible with versions of Sphinx below 6.2. …
> Upgrade sphinx to ~7.1.2

- .github/workflows/pythonpackage.yml
- doc/requirements.txt
This removes the specially cased alternative lower versions of `sphinx` and its dependencies that, since #1954, were only for Python 3.7. As discussed in comments there, this simplifies the documentation dependencies and avoids a situation where the version of Python used to build the documentation has a noticeable effect on the generated result.
This also conditions running the "Documentation" step in the main CI test workflow (`pythonpackage.yml`) on the Python version not being 3.7 (otherwise the job would always fail).
The only change this makes to the support status of GitPython on Python 3.7 is to no longer support building documentation on 3.7. GitPython can still be installed and used on 3.7 (though usually this would not be a good idea, outside of testing, since Python 3.7 itself …
> Don't support building documentation on Python 3.7

- git/index/base.py
- test/test_index.py
Working on Windows you sometime end up having some paths with backslashes (windows native) and some with slashes - this PR will resolve the issue using gitpython for those kind of cases (see example below). It will also fix the issues if paths contain redundant separators or "..".
```
import git
repo = git.Repo(r"C:\gittest")
repo.index.add(r"C:\gittest\1.txt")
repo.index.add(r"C:/gittest/2.txt")
repo.index.commit("test")
```
> _to_relative_path to support mixing slashes and backslashes

- .github/workflows/pythonpackage.yml
- git/cmd.py
- git/remote.py
See https://github.com/gitpython-developers/GitPython/issues/1969
stderr parser call RemoteProgress update on each line received. With universal_newlines set to False, there is a mixup between line feed and carriage return.
In the `handle_process_output` thread, this is thus seen as a single line for the whole output on each steps.
> Fix Fetch progress bar

- .github/workflows/alpine-test.yml
- .github/workflows/cygwin-test.yml
- .github/workflows/pythonpackage.yml
- test/test_git.py
This applies the fixes to GitPython that correspond to https://github.com/gitpython-developers/smmap/pull/58, as well as other fixes which were along the lines of the prediction in https://github.com/gitpython-developers/GitPython/commit/e51bf80ad576256f2fbeead41ea3f0b667c77055#commitcomment-150862474. Taken together, this fixes CI for GitPython.
The Cygwin and Alpine Linux failures were due to not using a virtual environment.
- In Cygwin, I had deliberately not done that, since we're not doing it the other non-container workflows, and I wanted the Cygwin workflow to be similar, with the hope that its job might even one day become a matrix job in `pythonpackage.yml`. But there had already been signs, accumulating over time, that this was not the way to go, such as the extra step to make …
> Fix various version-related CI breakages

- .github/workflows/alpine-test.yml
- .github/workflows/cygwin-test.yml
- .github/workflows/pythonpackage.yml
Neither #1955 nor #1988 is ready yet, but both include commits that clean up CI and that I think are already valuable. Some of the changes make GitHub Actions checks easier to read (8a05390, 41377d5), while another removes some complexity that is no longer needed (73ddb22). So I cherry-picked those commits onto a new feature branch, which this PR proposes merging. If this is merged, I'll rebase those other PRs to drop the corresponding commits from them. Details on the changes are in the commit messages.
> Do some CI cleanup to make reports clearer and future changes easier

- SECURITY.md
This expands `SECURITY.md` to affirm the claims in the new `SECURITY.md` files in gitdb and smmap that vulnerabilities found in them can be reported in the GitPython repository with the same link as one would use to report a GitPython vulnerability, as well as to note how the distinction between affected package can be specified when it is known at the time a vulnerability is reported.
Along with https://github.com/gitpython-developers/smmap/pull/59 and https://github.com/gitpython-developers/gitdb/pull/117, this fixes https://github.com/gitpython-developers/gitdb/issues/116.
> Affirm that gitdb and smmap advisories can also be created

- SECURITY.md
The links in #1991 did not work, as I got the branch names wrong. This fixes them.
> Fix links to gitdb and smmap `SECURITY.md` files

- .github/workflows/pythonpackage.yml
This enables testing Python 3.13 in the main CI test workflow for Ubuntu and macOS, as discussed in comments in #1989, but not Windows yet (pending #1955).
I think it makes sense to test these on CI, because:
- They're working now, and if they stop working, we would want to know.
- While Python 3.13 shouldn't be added as a classifier in `setup.py` yet since it's not fully working on Windows, testing other platforms on CI makes it easier for users to know they are meant (and believed) to work.
- The Ubuntu and macOS job are fast, so this probably isn't adding too much load, delay, energy usage, etc.
> Test Python 3.13 regularly on Ubuntu and macOS on CI

- git/repo/fun.py
- test/test_repo.py
This should resolve to commit object.
Fixes: #1995
> Repo.rev_parse: Handle <tag>^{commit} correctly

- fuzzing/fuzz-targets/fuzz_submodule.py
Hey there 👋 
As you may or may not have seen, the `fuzz_submodule.py` harness has been failing for some time now and I believe it is responisble for the "fuzzing build: failing" status on OSS-Fuzz.
I looked into it and it appears to be an issue with the test implementation, not GitPython.
The changes here should fix the issue causing the failure!
Please see the commit message for additional details.
> Fuzzing: Fix Broken Fuzz Test for Git Submodule Handling

- .github/workflows/cygwin-test.yml
I don't have a complete fix for #2004 yet, but since it's confirmed to fail on the main branch of this upstream repository (mentioned in https://github.com/gitpython-developers/GitPython/pull/1988#issuecomment-2680840638, though not due to #1988), I figured my partial fix might be worth putting into place. With these changes, the problem in the Cygwin test job turns from being unable to run any tests to being able to run all the tests but with one new failure compared to the way it was before #2004 (i.e. with one non-xfail failure).
This uses the official `pip` bootstrap script https://bootstrap.pypa.io/get-pip.py to install `pip` in the virtual environment. This allows the actual installation of GitPython and its dependencies, including all test dependencies, to complete without …
> Work around Cygwin CI failure #2004, except for `test_installation`

- test/test_installation.py
Together with #2007, this works around #2004, allowing all tests to pass on Cygwin CI.
In #2007, installation of the environment in which tests run was fixed by downloading and running the `get-pip.py` bootstrap script. If we were to modify our helper that sets up the (separate) virtual environment in `test_installation` so that it does the same thing (or conditionally does so on CI, since the problem does not seem to happen in local installations), that would likely "fix" this more thoroughly, allowing the test to pass.
But part of the goal of the installation test is to test that installation works in a typical environment on the platform it runs on. So it is not obivous that making it pass in that way would be an improvement compared to marking it `xfail` with the exception type that …
> Mark `test_installation` xfail on Cygwin CI

- git/index/base.py
- test/test_index.py
I encountered this issue on MacOS, python 3.7 and later
Added fix and appropriate unit test.
Stripping of trailing slash seems to be happening in `os.path.relpath`, altough I am not sure whether that is expected behaviour. In case it is not expected, and ever gets fixed, I added an additional check (` and not result.endswith(os.sep)`) to make sure that the trailing slash doesn't get duplicated.
> `IndexFile._to_relative_path` - fix case where absolute path gets stripped of trailing slash

- .github/workflows/pythonpackage.yml
Fixes #2005
See commit messages for details:
- f1dbe33 describes why this uses the approach of using a different action (rather than `@main` or `@...` where `...` is an OID) for the `3.13t` job, and why that is expressed by splitting the step instead of introducing a new matrix variable.
- fd78857 describes why this only introduces it for Linux. The reason is not entirely the same as proposed in [#2005](https://github.com/gitpython-developers/GitPython/issues/2005), since it turns out that testing on other systems--in the way we do so here--works without any special effort.
(As elsewhere, due to #2004, the Cygwin test job should be expected to fail here until #2009 is merged. That is not related to the changes here.)
> Test free-threaded Python (but only on Linux)

- git/refs/symbolic.py
- git/repo/base.py
It seems this type of properties are not supported by type checkers (mypy, pyright) and using `property` decorator fixes the issue.
```python
commit = property(
_get_commit,
set_commit,  # type: ignore[arg-type]
doc="Query or set commits directly",
)
```
See example below.
```python
import git
path = ""
repo = git.Repo(str(path), search_parent_directories=True)
reveal_type(repo.head.object) # Any
reveal_type(repo.head.commit) # Any
reveal_type(repo.description) # Any
reveal_type(repo.head.object) # AnyGitObject
reveal_type(repo.head.commit) # Commit
reveal_type(repo.description) # str
```
> Use property decorator to support typing

- git/index/base.py
- git/objects/base.py
- git/objects/commit.py
- git/repo/base.py
Fixed some markups so [the api reference](https://gitpython.readthedocs.io/en/stable/reference.html) is rendered correctly.
> Fix some incorrect sphinx markups in the docstrings

- .github/workflows/pythonpackage.yml
The changes in the fork were upstreamed and released in 5.5.0. See https://github.com/actions/setup-python/releases/tag/v5.5.0.
> replace quansight-labs/setup-python with actions/setup-python

- git/util.py
> remove type assertions from util.py

- .github/workflows/alpine-test.yml
- .github/workflows/cygwin-test.yml
- .github/workflows/lint.yml
Specify explicit `contents: read` workflow permissions
Three CI workflows that need only `contents: read` permissions and no other permissions did not have explicit permissions set, and would therefore be given default permissions configured for the repository, which might be more expansive than the workflows need.
[It is recommended][1] to set explicit workflow permissions. This does that, specifying permissions as `pythonpackage.yml` already did, and closing three `actions/missing-workflow-permissions` CodeQL alerts (new since #2032 enabled scanning of GHA workflows).
[1]: https://codeql.github.com/codeql-query-help/actions/actions-missing-workflow-permissions/
---
I'll merge this once I verify that all CI checks still pass.
> Specify explicit `contents: read` workflow permissions

- git/cmd.py
- requirements.txt
Fixes #2038
This fixes `mypy` for `Git.AutoInterrupt` and `Git.CatFileContentStream`. Static type checking of these was broken inadvertently in #2037, as described in #2038. This is approach (2) described in #2038. Further details are in that bug report and in the commit messages.
As in #2037, I've made sure this doesn't break Sphinx (though it would be very strange if it did), by checking locally as well as in the RTD cloud build. The entries in the latter can be examined: [`AutoInterrupt`](https://gitpython--2039.org.readthedocs.build/en/2039/reference.html#git.cmd.Git.AutoInterrupt), [`CatFileContentStream`](https://gitpython--2039.org.readthedocs.build/en/2039/reference.html#git.cmd.Git.CatFileContentStream).
Because CI runs `mypy` but does not verify its output, I'll wait to mark …
> Fix Git.{AutoInterrupt,CatFileContentStream} static typing

- .github/workflows/pythonpackage.yml
When the version is represented as `3.13t`, the `--python-version` option needs an operand of `3.13`, not `3.13t`.
(This, and the fix here, will automatically apply to later threaded Pythons, such as 3.14t, too.)
---
Before this change, [in the Python 3.13t run](https://github.com/gitpython-developers/GitPython/actions/runs/15509622156/job/43668845392#step:11:14):
```text
+ mypy --python-version=3.13t
usage: mypy [-h] [-v] [-V] [more options; see below]
[-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: argument --python-version: Invalid python version '3.13t' (expected format: 'x.y')
```
This isn't new--it's always happened in the `mypy` step in the 3.13t job. We just never noticed it, because the `mypy` step always reports failure even when working correctly, because …
> Fix CI `mypy` command on free-threaded Python

- .github/workflows/cygwin-test.yml
One job is for all tests except the `performance` tests, while the other job is for only the `performance` tests.
The idea is to decrease the total time it takes for all CI jobs to complete in most cases, by splitting the long-running (currently usually about 13 minute) Cygwin job into two less-long jobs.
[This seems to work well.](https://github.com/EliahKagan/GitPython/actions/runs/15510202755/job/43670134782) The performance tests take longer than all the other tests combined. Even with the other steps--mainly setting up Cygwin--taking about 2.5 minutes, this still completes significantly faster than before by allowing the jobs to run in parallel.
A secondary advantage is that incomplete results of tests that are more often of interest can be seen sooner. (I say that's secondary …
> Split Cygwin CI into non-`performance` and `performance` test jobs

- .github/workflows/alpine-test.yml
- .github/workflows/cygwin-test.yml
- .github/workflows/pythonpackage.yml
- test/lib/helper.py
In `pip` commands that conditionally install/upgrade or disregard `setuptools`, this uses the static but version-discriminating specification `setuptools; python_version<"3.12"`, rather than conditionally including or omitting a `setuptools` argument as was done before.
This covers the two scenarios where this applies, in separate commits:
- 31e1c035e1af514d5d2a9ed6630f71663df7b265: The `VirtualEnvironment` test helper class (where this functionality is relevant in how `test_installation` uses `VirtualEnvironment`).
- 727f4e9e54362d0356066a26d0c22028a465cccd: The steps for upgrading PyPA packages in CI workflows.
> Express conditional `setuptools` requirement statically

- git/cmd.py
This fixes some ambiguous wording in a comment in `_safer_popen_wording`, where it was unclear if the secondary problem – where it would be possible to run a wrong `cmd.exe`-type shell – would happen under two separate circumstances, or only when both circumstances occurred together. This adjusts its wording to make clear that it is the latter.
This also fixes a minor typo in another `_safer_popen_windows` comment.
This might be viewed as building on the improvements in b9d9e56 (#1859), but the changes here are to comments only.
(I'll merge this once CI passes on it.)
> Fix ambiguous `_safer_popen_windows` comment

- git/cmd.py
This is a minor refactor of how `_warn_use_shell` can be, and is, invoked.
The `_warn_use_shell` helper function in `git.cmd` takes a single `bool`-valued argument `extra_danger`, which is conceptually associated with having a `True` value of `USE_SHELL`, but the association is not necessarily obvious. Specifically:
- For the warning given when reading `USE_SHELL` on the `Git` class or through an instance, `extra_danger` is always `False`. This is so even if the `USE_SHELL` value is currently `True`, because the danger that arises from `True` occurs internally.
- For the warning given when writing `USE_SHELL`, which can only be done on the `Git` class and not on or through an instance, `extra_danger` is the value set for the attribute. This is because setting `USE_SHELL` to `True` incurs …
> Clarify `USE_SHELL` warning helper signature

- git/config.py
- test/fixtures/git_config_with_empty_quotes
- test/test_config.py
One of the benefits of #2035 is that it automatically handles a quoted empty value, i.e. `name = ""`, correctly. Previously, this was handled as a special case, so that it would work even though other quoted values did not work (#1923). Since #2035, it is not necessary to handle it specially. Accordingly, this PR:
- Adds a regression test for values represented as `""` (4ebe407493363a814f590a97f3734364e6c5c1e1).
- Removes the obsolete special-case logic (2f225244286567b72c865fc7c0219c7dc043575f).
> Remove explicit empty `""` handling in ConfigParser

- git/config.py
- test/fixtures/git_config_with_quotes_escapes
- test/test_config.py
#2035 fixed issue #1923, where the ConfigParser would not remove the quotes around single-line values. As discussed in comments there:
- That improved the common cases where quote removal is all that is needed, in particular where no escape sequences are present.
- When there are escape sequences within a single line quoted value, that was already not handled correctly--since no single-line quoted values (other than a quoted empty string) had been handled correctly before [#2035](https://github.com/gitpython-developers/GitPython/pull/2035), in that quote removal was never performed for them.
- Nonetheless, [#2035](https://github.com/gitpython-developers/GitPython/pull/2035) may have made the situation worse for some applications if they handled the quoted values themselves, or if the …
> Don't remove quotes if `\` or `"` are present inside

- git/objects/submodule/base.py
- test/test_submodule.py
This fixes running repo.update_submodules(init=True) on repositories that are using relative for the modules.
It tries to emulate the git behavior: https://github.com/git/git/blob/master/builtin/submodule--helper.c#L503
Fixes #730
> fix updating submodules with relative urls

- setup.py
- test/test_installation.py
The main way we indicate the license in the project's metadata is:
https://github.com/gitpython-developers/GitPython/blob/46c439b5d3b8c8fa26d5b305b31d6cd189e42210/setup.py#L72
However, we have for some time, until this PR, also had a trove classifier indicating "BSD License":
https://github.com/gitpython-developers/GitPython/blob/46c439b5d3b8c8fa26d5b305b31d6cd189e42210/setup.py#L98
This has a couple of problems. One is that there is no specific "BSD License", but instead various BSD licenses, of which two are very popular: BSD-3-Clause, which this project uses, and BSD-2-Clause, which is not what this project uses. (No PyPI-recognized trove classifiers for those specific BSD licenses exist.)
The other problem is that *all* usage of `License :: ...` trove classifiers has been deprecated. …
> Fail `test_installation` on warnings, and remove deprecated license classifier

- git/objects/submodule/base.py
- test/test_submodule.py
> Allow relative path url in submodules for submodule_update

- git/config.py
- test/test_config.py
Support adding custom paths for the following git config:
```
[includeIf "hasconfig:remote.*.url:**/**github.com*/**"]
path = ~/.personal.gitconfig
```
According to the documentation:
> As for the naming of this keyword, it is for forwards compatibility with a naming scheme that supports more variable-based include conditions, but currently Git only supports the exact keyword described above.
So I have matched the condition exactly word to word with `hasconfig:remote.*.url`. I then go over the list of remotes and find using `fnmatchcase` the correct remote (not sure if `fnmatch`. 
Maybe a list of open points here:
- I'm not sure if the wildcard format and the fnmatch function are equivalent. Is it necessary to match these two 100%? Maybe a maintainer would have more experience with
- …
> feat: Add support for hasconfig git rule.
